### ISSUE TITLE
ToolCamera = Error

### ISSUE THREAD

**Issue by mngrazy** [Mogli12/KeyboardSteer#1]
hi biedens

ich hab mit der aktuellen version (1.8.9.2) von keyBoardSteer ein problem mit den ToolCameras von Giants.
sobald ich z.b. auf die Cam wechsel beim Jenz Hacker haut mir keyBoardSteer einiges in die log

keyboardSteerMogli.lua:599: table index is nil
mogliBase.lua (449): ksmSetState
keyboardSteerMogli.lua (158): update
[string "D:/code/lsim2015/build/finalbin/dataS/scripts/vehicles/Vehicle.lua"] (2549): update
[string "D:/code/lsim2015/build/finalbin/dataS/scripts/network/Server.lua"] (56): update
[string "D:/code/lsim2015/build/finalbin/dataS/scripts/BaseMission.lua"] (1185): update
[string "D:/code/lsim2015/build/finalbin/dataS/scripts/FSBaseMission.lua"] (1566): orig_update
3 3 nil

gibts da eine lösung ? 

grüsse grazy

**Comment by Mogli12** [comment]
Hi Grazy,
Es sollte mit dem letzten Update korrigiert sein.
Vielen Dank, Mogli

**Comment by mngrazy** [comment]
fixed ,,,, läuft nun ohne fehler ! danke Mogli :)

grüsse grazy
