### ISSUE TITLE
Compass direction is incorrect

### ISSUE THREAD

**Issue by Harag9** [Mogli12/KeyboardSteer#100]
The compass bearing at the corner is incorrect when going E / W it shows 270 when going east and 90 for west.

**Comment by DonPaul75** [comment]
Hi, danke fur Deine arbeit und freue mich schon auf da GB fur ls19. Hoffentlich kommt. 
Bis dann habe ich die umsetzung fur KeyboardSteer fur CZ/SK spieler gemacht.

[modDesc_l10n_cz.zip](https://github.com/Mogli12/KeyboardSteer/files/2729574/modDesc_l10n_cz.zip)

**Comment by goelmc2** [comment]
This fixes the compass
@ line 867 make the following changes
	local lx,_,lz = localDirectionToWorld( self.components[1].node, 0, 0, 1 )
	lx = lx * -1
	if lx*lx+lz*lz > 1e-6 then 
		renderText(x, y, l, string.format( "%4.1f°", math.deg( math.atan2( lx, lz ) + math.pi )))
	end 
	
	y = y + l * 1.1	
	if self.ksmLastSnapAngle ~= nil then
		renderText(x, y, l, string.format( "%4.1f°", math.abs(math.deg( self.ksmLastSnapAngle - math.pi))))
	end

**Comment by schudor** [comment]
Hi goelmc2
I think there is a little mistake. 
The line "if lxlx+lzlz > 1e-6 then" must be as the original "if lx*lx+lz*lz > 1e-6 then".
In my Mac it works only with the original line.
Sorry for my bad english, it's 50 years ago since I had it in school.

**Comment by Harag9** [comment]
thanks for the above guys, I'll look at putting the change into my version. Hopefully Mogli can add it into the main mod.

Can we just update the .lue file in the zip file and it will recompile automatically when it loads?

**Comment by Mogli12** [comment]
Hi,
Currently, I am waiting for version 1.0 to be tested and published at [ModHub](https://www.farming-simulator.com/mods.php).
Regards,
Stefan

**Comment by goelmc2** [comment]
Thank you, sounds good and great to have it ! :) Snap angle is a great way to hold your course.

**Comment by Harag9** [comment]
Love the snap angle - use it all the time since all the field most of the time are always on n/s e/w facing so the setting of 90' is very useful.

However I was referring to the compass direct pointing the wrong way (E is 90, not 270). Has this been correct since v0.0.3.1 (which is my current version).

**Comment by Harag9** [comment]
Downloaded the latest version yesterday and it worked fin in that!. I know newer versions have been out since.
