### ISSUE TITLE
Differentialsperre 2WD/4WD

### ISSUE THREAD

**Issue by Tensuko** [Mogli12/KeyboardSteer#106]
Hi,
super Mod bisher und gerne genutzt, auch dass die Einstellungen pro Fahrzeug und Ansicht gemacht werden können ist genial.
Ich hätte aber doch einen Wunsch als Erweiterung der Mod.
Differentialsperre an/aus und umschalten zwischen 2WD und 4WD würde glaube ich supper zur Mod passen.
Die Mod EnhancedVehicle macht dies zwar schon, jetzt wurde da aber auch noch Shuttle mit eingebaut und das ist eine Doppelentwicklung, die sich wohl kaum miteinander vertragen würden. Das ist das einzige, was ich bei EnhancedVehicle wirklich bräuchte, wäre das hier mit drin, könnte ich auf die andere Mod verzichten oder nur die Damage-Anzeige davon verwenden.

Ist halt immer schade, wenn an einigen Funktionen doppelt gearbeitet wird und sich dadurch Mods gegensitig ausschließen.

**Comment by bgo1973** [comment]
Das Shuttle-Control kannste doch in den Einstellungen deaktivieren.

**Comment by Mogli12** [comment]
Leute, ich habe bereits mehrfach geschrieben, dass ich auf dieses Spielchen mit Inkompatibilitäten keine Lust habe. Der Entwickler von TSX_EnhancedVehicle kennt sicher KeyboardSteer. Dass er nun trotzdem auch noch Shuttle Control in TSX_EnhancedVehicle einbaut ist alles andere als nett.

Das ist auch der Grund, warum ich GearboxAddon einstelle, in dem ja Shullte Control und Differentialsperren in FS17 auch drin waren. Sobald KeyboardSteer im [ModHub](https://www.farming-simulator.com/mods.php) veröffentlicht ist, höre ich auf mit Modding.
