### ISSUE TITLE
Light issues

### ISSUE THREAD

**Issue by knuuud** [Mogli12/KeyboardSteer#108]
Lights for brakes and rear lights mix up and turn on with brakes. Also brakelight should not activate when releasing accelerator.

**Comment by Mogli12** [comment]
Please look at (README.md)[https://github.com/Mogli12/KeyboardSteer] and provide log.txt, version number and a screen shot.

**Comment by knuuud** [comment]
There is nothing in the log, and its the only mod in my modsfolder during testing. Also you cant miss it when turning on lights and driving. Same goes for the brake ligghts. they turn on as soon as you let go of the accelerator. You have a brakepedal for that ;)

**Comment by Mogli12** [comment]
Without further details I cannot reproduce it.
