### ISSUE TITLE
Rückwärtsgang funktioniert nicht (V0.0.3.2)

### ISSUE THREAD

**Issue by Z3t3r** [Mogli12/KeyboardSteer#111]
Hallo Mogli12,
immer wenn ich in den Rückwärtsgang beim 2x6 er Getriebe schalte wird mein Screen buggy (siehe [Bild)](https://drive.google.com/open?id=1zCHS5HFqT7zxKPSWLkVHzKTM2eD15Uop) und Rückwärts fahren ist auch nicht drin. Zusätzlich setzt sich die Option Shuttle Control auf aus. Ich nutze den Logitech Schalthebel fürs G29. Währe nett wenn du das Beheben kannst sodass wenn ich in den Rückwärtsgang Schalte ich auch wieder Rückwärts fahren kann.
Danke.

**Comment by Mogli12** [comment]
Ich denke, dass man beim Schalthebel unbedingt ShuttleControl eingeschaltet lassen muss. TSX_VehicleExtension darf auch nicht aktiv sein, weil es (ohne Absprache) ShuttleControl ausschaltet.

**Comment by Z3t3r** [comment]
Shuttle Control ist an wird jedoch deaktiviert wenn ich in den rückwärts Gang schalte, selber Effekt auch, wenn ich den Rückwärtsgang auf eine Tastaturtaste lege. TSX_VehicleExtension hab ich nicht auf meinem PC. 
Danke aber für deine schnelle Antwort

**Comment by Z3t3r** [comment]
Ach, vergessen zu erwähnen, Shuttle Control ansich funktioniert mit dem Getriebe es geht hier nur um den Punkt des Rückwärtsganges (letzter Punkt bei den Einstellungen zum Tastenbelegen)

**Comment by Z3t3r** [comment]
Kannste schließen funktioniert in der aktuellen Version 0.0.3.8
