### ISSUE TITLE
Runterschalten beim FPS Getriebe

### ISSUE THREAD

**Issue by Fracking** [Mogli12/KeyboardSteer#112]
Hallo Stefan,
mir ist aufgefallen, dass das manuell Runterschalten mit dem FPS (FullPowerShift) Getriebe nicht möglich ist.
In keyboardSteerMogli.lua fehlt nach Zeile 607 der entsprechende Eintrag für das FPS Getriebe.
`or self.ksmTransmission == 5` Fehlt
Ich kenne mich da nicht so aus, aber so funktioniert es bei mir:

elseif actionName == "ksmGearDown"  then 
		if     self.ksmTransmission == 2
				or self.ksmTransmission == 3
                                or self.ksmTransmission == 4
				or self.ksmTransmission == 5 then
			if self.ksmGear > 1 then 
				self:ksmSetState( "ksmGear", self.ksmGear - 1 )
			end 
		end 

Grüße

Andreas

EDIT: Das bezieht sich auf die Version 0.0.3.3

**Comment by Mogli12** [comment]
Hallo Andreas,
das sollte seit 0.0.3.5 behoben sein.
Viele Grüße, Stefan
