### ISSUE TITLE
Keyboardsteer bricht Förderbandnutzung

### ISSUE THREAD

**Issue by breadcan** [Mogli12/KeyboardSteer#117]
Mit der aktuellen Version kann man keine Förderbänder mehr bewegen.

**Comment by Mogli12** [comment]
Hallo,

kannst Du bitte ein paar Details hinzufügen? Ein Screen shot wäre sicher hilfreich, Und bitte lade die log.txt in [Gist](https://gist.github.com/) hoch.

Danke

**Comment by ZhooL** [comment]
Den Effekt des "doppeln" hatte ich auch mal. War bei allen Attachments, die selbst motorized sind. Konnte ich lösen durch:
-  -- only in active vehicle
-  if isOnActiveVehicle then
+  -- only in active vehicle and when we control it
+  if isOnActiveVehicle and self:getIsControlled() then

**Comment by Mogli12** [comment]
Ich habe beim Laden des Mods noch etwas angepasst. Tritt es noch in VehicleControlAddon auf?

**Comment by breadcan** [comment]
Fixed
