### ISSUE TITLE
settings?

### ISSUE THREAD

**Issue by ivanlii** [Mogli12/KeyboardSteer#12]
Hi, Mogli
1 .what are this settings: 
timer4Reverse
enableAnalogCtrl
axisForwardGearbox ?

2. is it possible to disable reverseCamera for external view globaly ?

3. i use this mod together with Decker_MMIV`s QuickCamera mod:
[https://www.farming-simulator.com/mod.php?lang=en&country=gb&mod_id=54506&title=fs2017](url)
and there is a small conflict: when KeyboardSteer-reverseCamera is on and i use QuickCamera-look back 
camera rotates back and then returns automatically forward.

Thank you for your time!

**Comment by Mogli12** [comment]
Hello Ivanii,

You can create a file keyboardSteerMogliConfig.xml directly in the mods folder and change these flags:
```xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<KSMGlobals>
	<ksmSteeringIsOn     type="bool"  value="true"/><!-- change steering at higher speed -->
	<ksmCameraIsOn       type="bool"  value="false"/><!-- rotate camera -->
	<ksmCamInsideIsOn    type="bool"  value="true"/><!-- override ksmCameraIsOn for internal cam -->
	<ksmReverseIsOn      type="bool"  value="true"/><!-- automatically look back -->
	<ksmDrawIsOn         type="bool"  value="false"/><!-- show help texts in the F1 window -->
	<enableAnalogCtrl    type="bool"  value="false"/><!-- change steering for analog controllers as well -->
</KSMGlobals>
```
I copied these values with the current default value. 

Best regards,
Mogli

**Comment by ivanlii** [comment]
Hi Mogli, is there a way to disable camera movement for reverse driving, i remember i had something in FS15.
Thank you
