### ISSUE TITLE
Rückwärtsgang fehler L6

### ISSUE THREAD

**Issue by Z3t3r** [Mogli12/KeyboardSteer#120]
Hey,
wenn ich beim 2x6er Getriebe in der hohen Gruppe in den Rückwärtsgang schalte und dann ins kleine Getriebe wechsle bin ich im L6 aber halt als Rückwärtsgang! Sollte ja normalerweise nur L1 Rückwärts geben! Version 0.0.3.8
Gruß Z3t3r

**Comment by Mogli12** [comment]
Hallo Z3t3r,
Nutzt Du die Tastatur oder einen Ganghebel?
Gruß, Stefan

**Comment by Z3t3r** [comment]
Ganghebel

**Comment by Mogli12** [comment]
Beim Wechseln des Getriebes kann das sein. Im Gegensatz zu alten LS Versionen wird im LS19 das Script nur noch aufgerufen, wenn sich eine Taste ändert. Daher muss man nach dem Wechseln des Getriebes einmal am Ganghebel einen Vorwärts- und einen Rückwärtsgang betätigen.
