### ISSUE TITLE
Sugestion: Player model pressing brake pedal when brake light is showing

### ISSUE THREAD

**Issue by knuuud** [Mogli12/KeyboardSteer#126]
Hey, I like the updated name 👍  More fitting to the mod 👍 

When the machines in the game are standing still , pressing the brake key only lights the brake lights. Is it possible to make the player model press the brake pedal as well like when the machine is braking from speed?

(an additional idea for this is the shutting off of the turn signals when you made the turn (like most machines IRL.)

Regards
Knut A.

**Comment by bgo1973** [comment]
Ifko already made converted his mod for atomatically turn off the turnlights. It's "FS19_autoTurnOffTurnLights.zip".

**Comment by Mogli12** [comment]
Hi Knut,

Thanks for the feedback. 

I think the animation of the player is done based on the axisForward values. I do not really think that this is something that could be done in VCA. BrakeLights and ReverseLights are set in WheelsUtil.

Regards,
Stefan

**Comment by knuuud** [comment]
ah ok :) I just thought it could be linked :)

**Comment by knuuud** [comment]
I know you closed this, just wondering if this is something that could be used? 

https://gdn.giants-software.com/documentation_scripting.php?version=script&category=69&class=3545#updateWheelsPhysics48082

line 137 ->

sorry for the bother. :)

**Comment by knuuud** [comment]
This is now working on shuttle backwards, should it not also work on shuttle forwards than? :)
