### ISSUE TITLE
'keyboardSteerMogli.lua:642: attempt to compare nil with number' error when trying to use the train

### ISSUE THREAD

**Issue by fdanapfel** [Mogli12/KeyboardSteer#13]
Using FS17_KeyboardSteer Version: 2.1.1.3 the log gets flooded with the following error as soon as one of the trains on Goldcrest Valley is entered:
```
Error: Running LUA method 'update'.
/Users/frank/Library/Application Support/FarmingSimulator2017/mods/FS17_KeyboardSteer/keyboardSteerMogli.lua:642: attempt to compare nil with number
```
When using other vehicles this error doesn't occur.

Also with Version 2.1.1.3 the log contains the following warnings if the language of the game is set to something other than German:
```
Warning: Missing l10n for button ksmTPLUS in FS17_KeyboardSteer
Warning: Missing l10n for button ksmTMINUS in FS17_KeyboardSteer
```

**Comment by Mogli12** [comment]
Hi,
Please check beta 4.
Thanks, Stefan

**Comment by fdanapfel** [comment]
Thanks, with beta 4 there are no more errors when using the train and the warnings have disappeared as well.
