### ISSUE TITLE
Unable to drive after sleeping at night!

### ISSUE THREAD

**Issue by Jayshua83** [Mogli12/KeyboardSteer#131]
Anyone else having issues when you sleep thru the night you can't drive anything until you restart the game?

My wife and I both are having this problem on a Dedicated Server!

**Comment by vone** [comment]
We have the same issue on our dedi server. I will post log later when i get home from work.

**Comment by wriley** [comment]
Same issue here on our dedicated server. Versoin 0.0.0.6. Unable to drive any vehicle after sleeping with farmhouse. Nothing in log on client or server. Brake and reverse lights work but no rpm change or movement on any vehicle.

**Comment by Mogli12** [comment]
Did you try to choose transmission "off" in the settings? Did you turn on/off the motor? Did you press the Neutral button?

In single player it is no problem to drive vehicles with 4X4 transmission after sleeping.

**Comment by wriley** [comment]
Vehicle transmissions are all default IVT. Turning on/off motor makes no difference. I didn't know there was a neutral button so didn't press it.

**Comment by wriley** [comment]
Video demonstrating the issue https://www.youtube.com/watch?v=515dR2IPL64

**Comment by Jayshua83** [comment]
On our server I have it set for Giants Transmission and Auto Transmission.

**Comment by Mogli12** [comment]
These are the same errors as in #124. Let's continue there.

**Comment by wriley** [comment]
These errors don't show up every time, I just included them because they happened to pop up

**Comment by Jayshua83** [comment]
I am NOT getting ANY errors in my log! Above error is not related maybe?

**Comment by wriley** [comment]
I'm going to do some testing on a clean Ravenport start with only mod being VCA on our server and report back. I don't think this is related to #124

**Comment by wriley** [comment]
Confirmed this bug on a new game on our dedi server with VCA being the only mod. I replicated the activities in my video above and got the same results. After using the farmhouse to sleep unable to drive. I let the game go through the night at 120x speed and could drive normally the next day so seems related to the sleep function. Full client and server logs attached.
[client_log.txt](https://github.com/Mogli12/KeyboardSteer/files/2774019/client_log.txt)
[server_log.txt](https://github.com/Mogli12/KeyboardSteer/files/2774020/server_log.txt)

**Comment by Mogli12** [comment]
And you are sure that the problem does not appear w/o VCA? I cannot see any error in the log. The consequence of it is that I will disable this mod completely for MP.

**Comment by wriley** [comment]
This behavior only started recently, we've been using KS on the server for weeks and have used sleep function many times. I will test some more to confirm.

**Comment by wriley** [comment]
I tested a bunch of different versions and found that 0.0.3.1 does not have this bug. That's the version we've used the longest on the server and only recently upgraded to try out the new gearbox feature.

VCA 0.0.0.6 bug
VCA 0.0.0.3 bug
KS  0.0.4.0 bug
KS  0.0.3.9 bug
KS  0.0.3.1 no bug

**Comment by Mogli12** [comment]
And 0.0.0.8?

**Comment by wriley** [comment]
Whoa, you're fast. I didn't see those updates after 0.0.0.6. :) Will test

**Comment by wriley** [comment]
bug still present in 0.0.0.8

VCA 0.0.0.8 bug
VCA 0.0.0.6 bug
VCA 0.0.0.3 bug
KS  0.0.4.0 bug
KS  0.0.3.9 bug
KS  0.0.3.1 no bug

**Comment by Mogli12** [comment]
Ok, dann schalte ich MP jetzt aus.
