### ISSUE TITLE
default settings for automatic gearchange

### ISSUE THREAD

**Issue by cabmac** [Mogli12/KeyboardSteer#133]
hi, ich glaube es gibt in der default config kein setting, um die "Automatik" abzustellen... koenntest du das noch einbringen, das man die nicht bei jedem SV-Neustart und bei jedem Fzg neu abstellen muss?

Schoene Gruesse

**Comment by Mogli12** [comment]
Ab Version 0.0.0.6 wird es korrekt im Savegame gespeichert.
