### ISSUE TITLE
Keyboardsteer MP fehler mit LOG

### ISSUE THREAD

**Issue by QuadRowdy86** [Mogli12/KeyboardSteer#134]
Hey Ho.
Mogli12 danke für deinen mod, muss mal gesagt werden.
Ich habe mich gerade zum ersten mal auf github registriert und kenne mich hier nicht wirklich aus.

Aber nun zum eigendlichen Thema, ich habe deinen Mod auf meinen Community Server mit drauf und der Bring mir eine Warning in der Log, ist nur eine Warning ich weis trotzdem möchte ich es mit dir (euch) teilen, vllt fndet sich ja der Fehler.

https://bit.ly/2HeRU5s <--- Hier gehts zur log. In Zeile 76 steht der Fehler.

**Comment by Mogli12** [comment]
Hallo,
Danke fürs Danke.
Allerdings verwendest Du immer noch FS19_KeyboardSteer. Bitte lösche diesen Mod und verwende stattdessen FS19_VehicleControlAddon. Und dann kann ich ab Zeile 76 keinen Fehler finden. Da steht nur eine Warnung, die außerdem bereits korrigiert ist.
Viele Grüße,
Stefan

**Comment by QuadRowdy86** [comment]
Danke für das schnelle antworten.

Danke für den hinweis, habs gerade geladen. Dann darf (kann) hier geschlossen werden.

Danke.
