### ISSUE TITLE
vehicleControlAddon.lua : 2166

### ISSUE THREAD

**Issue by Jayshua83** [Mogli12/KeyboardSteer#136]
Still not sure how to use GitHub and upload changes or if you even allow it but here is a line that could be changed? :) Thanks

vehicleControlAddon.lua
2166
OLD = self.vcaUI.vcaTransmission = { "off" }
NEW = self.vcaUI.vcaTransmission = { "Off" }

**Comment by Mogli12** [comment]
The string "off" is just a placeholder. This mod is work in progress. Please read the README.md.
