### ISSUE TITLE
4x4 schaltet bei Gang 5 und 6 nicht mehr die Gruppen

### ISSUE THREAD

**Issue by breadcan** [Mogli12/KeyboardSteer#138]
"In case of a 4x4 transmission the gears 5 and 6 are used to shift the range down or up." scheint seit 1-2 Versionen nicht mehr zu funktionieren.

Bei 4x4 und einlegen von Gang 5 erscheint im HUD:

![image](https://user-images.githubusercontent.com/416166/51404960-3bbe2d00-1b55-11e9-9bbb-d0c9046f1386.png)

Aktuelle Version 0.0.0.7, Neues Savegame, keine anderen Mods und Fiat 1300DT Traktor.
[log.txt](https://github.com/Mogli12/KeyboardSteer/files/2774041/log.txt)

**Comment by Mogli12** [comment]
Ja, das habe ich ausgebaut, weil es zu viele Verwirrungen gab. Mit den 6 Gängen und vcaShifterLH schaltet man jetzt alle Gänge. Es sind zwar rechnerisch 16 Gänge, aber einige habe dieselbe Übersetzung.
