### ISSUE TITLE
Analogue controller option issue with GPS mod

### ISSUE THREAD

**Issue by Dwinesk** [Mogli12/KeyboardSteer#14]
Hi,
If you activate the analogue controller option and then try using the GPS mod, the steering wheel in cab of the vehicle you are using flickers weirdly as it steers to auto correct. Could this be sorted out so that the steering animation remains as smooth as without that option selected?

P.s. Thanks for all the hard work on all your mods.

**Comment by Dwinesk** [comment]
Any luck with this issue?

**Comment by Mogli12** [comment]
No. I do not use the GPS mod. But I guess that KeyboardSteer tries to smooth the steering information coming from GPS mod. The only work around is to disable KeyboardSteer for analog controlelrs.

**Comment by Dwinesk** [comment]
Is it possible to add code that only disables KeyboardSteer for analog controllers when GPS mod is activated for that specific machine in use? So that as soon as you deactivate the GPS in-game, if you were using the analog controller option, it immediately return to those settings?

**Comment by Mogli12** [comment]
Please check version 2.2 beta 9 or 10.

**Comment by Dwinesk** [comment]
Feels like its working quite well now. Thanks
