### ISSUE TITLE
seriously

### ISSUE THREAD

**Issue by knuuud** [Mogli12/KeyboardSteer#140]
This is your reason for quitting modding? I would have understood if you where bored or whatever, but a bump in the road ftom Giants throws you off? Modding are NOT done for Giants, its done for fun and for the players! of all players I heard about only 2% uses the sleep function on a dedi server, now what about the rest of us? I still think you are a good modder, but I still think giving up because of something a minority uses thats bad.

Sorry I had to have my say even if you only delete it and don't care about what I say.

Knut A. 
[log.txt](https://github.com/Mogli12/KeyboardSteer/files/2775169/log.txt)

**Comment by Jayshua83** [comment]
I freaking agree, and I am one of the minority. I'll give up sleeping on a Dedicated server to keep this alive or I'll just reboot it every game night, who cares? Lol! 

No idea why it's so easy to give up!

**Comment by DonPaul75** [comment]
To show the potential of your mod, I made a short video as a motivation for the contestants. This is what I've also published in Forum Gigant. Even if only 2%, it is still more than 20 000 potential customers. Please make your way to the Giant and keep your work alive, it's great.

https://www.youtube.com/watch?v=3_vH89INiPE

Please add a real clutch, this will be another great step in the right direction
Thanks for Your Work, it's Great.

**Comment by Mogli12** [comment]
The problem seems to be that something (e.g. garbage collection?) destroys classes I created for the different transmissions. With this bug I cannot publish the mod on ModHub. So this is a show stopper.
