### ISSUE TITLE
Problem kein Fahren möglich nachdem man geschlafen hat

### ISSUE THREAD

**Issue by dl1esk** [Mogli12/KeyboardSteer#141]
Hallo Stefan,

ich habe das ganze eben mal reproduziert und tatsächlich kann man nachdem man geschlafen hat kein Fahrzeug mehr fahren.
Nach einem Server neustart ist jedoch alles wieder super.
Kann es denn sein das es i-was mit der Server Zeit zu tun hat ?!

**Comment by Mogli12** [comment]
Hallo,
Du kannst noch Version FinalBugFix probieren. Ansonsten geht es hier nicht mehr weiter. Dieser Fehler tritt im SP nicht auf. Ich habe keine Ahnung, warum Schlafen auf dem Dedi überhaupt etwas am Fahrzeug ändert. Ich sehe also keine Perspektive, diese Problem überhaupt zu lösen. Da man den Mod so nicht in ModHub veröffentlichen kann, gebe ich auf.
Gruß,
Stefan
