### ISSUE TITLE
Gearbox repository

### ISSUE THREAD

**Issue by Dwinesk** [Mogli12/KeyboardSteer#18]
"This repository has been archived by the owner. It is now read-only.". Appears at the top of the gearbox repository page and makes it impossible for anyone to even comment on the issues one has found with the mod (be that good or bad things). Please do something about that. I'd like to keep contributing to that mods development. Please and thank you.

**Comment by KITT3000** [comment]
You probably did not read the entry that he added to README:
>**Taking a Break**
I have noticed that I do not play Farming Simulator anymore. I just check from time to time if the gearbox addon is working the way I wanted it to be. But overall I am a little bit tired and I will pause this project for now.

**Comment by Dwinesk** [comment]
I didn't see that. Thank you.
