### ISSUE TITLE
Suggestion: autoRotateBackSpeed delayed start

### ISSUE THREAD

**Issue by timbwana** [Mogli12/KeyboardSteer#22]
Great mod, just one minor tweak would be good - if there can be a small delay (say 0.2 Seconds) before the steering wheel rotates back to centre. Currently as soon as you release "A" or "D" the auto rotation starts immediately.

**Comment by Mogli12** [comment]
Hi,
Starting from about line 600 in keyboearSteerMogli.lua there is already some kind of reduction of autoRotateBackSpeed.
Regards, Stefan
