### ISSUE TITLE
Not an issue, more of a request.  Local Settings Save.

### ISSUE THREAD

**Issue by sphynx1492** [Mogli12/KeyboardSteer#23]
Would you please look at creating a local XML file to save the settings I have for my vehicles when playing on a dedicated server?  Maybe just by type if that is easier.

Example:  I have some vehicles that I can't see out the back window, or that I like to use the mirrors, so I have to disable the look backwards feature.  I would like it to save for that vehicle so I don't have to change the setting ever time I log back onto my server.

**Comment by Mogli12** [comment]
Hi,
I think we have to wait until the luadoc is published to see how saving settings works.
Regards, Stefan

**Comment by Jayshua83** [comment]
Both of these mods already save their settings into the modSettings folder!!

https://www.modhoster.com/mods/vehiclefruit-hud
https://www.modhoster.com/mods/vehicleinspector--2

**Comment by Mogli12** [comment]
VCA now uses mod settings in `.../modSettings/FS19_VehicleControlAddon/vehicleControlAddonConfig.xml".

**Comment by Mogli12** [comment]
Project is stopped as it does not work together with sleep on Dedi server.
