### ISSUE TITLE
FS19_KeyboardSteer inputs

### ISSUE THREAD

**Issue by ivanlii** [Mogli12/KeyboardSteer#25]
First of all, thank you very much for porting this mod to FS19, Stefan!
Can i suggest some different inputs, hope you don't mind:
- default look forward
- look left/right with key hold (or switch left/forward right/forward)
- single input for switching forward/back look
And of course input bindings for future versions.
Thank you again, must have mod!

**Comment by Mogli12** [comment]
Hi,
InputBindings are available now.
Regards, Stefan

**Comment by Eepsquared** [comment]
How about an option to use a key hold instead of toggle? Example: look back holding spacebar but let go and camera returns to front.

**Comment by Eepsquared** [comment]
Also need a way to keep acceleration going when looking back.

**Comment by Mogli12** [comment]
I think we are very limited if we want to have actions if a key is pressed. We would need 4 different keys that are not used for something else.

I prefer to have normal input bindings. If you press space the driving direction changes. If you presse it again it changes again.

**Comment by Eepsquared** [comment]
Well how can I disable the driving direction change and still keep the "look behind" functionality?

**Comment by Mogli12** [comment]
LCtrl+C
