### ISSUE TITLE
No issuem made a dutch translation.

### ISSUE THREAD

**Issue by Div3rsion** [Mogli12/KeyboardSteer#26]
Hi Mogli.
I made a dutch translation for keyboardsteer fs19.

How do I get it over to you. It is in my fork from keyboard steer.

Regards,
Rick

**Comment by Mogli12** [comment]
Hi Rick,

I think you have to create a merge pull request.

Thanks and regards,
Stefan

**Comment by Div3rsion** [comment]
made a pull request. Hopefully it works. 
If succesfull and if look like I can continue to translate futher mods in Dutch for you

**Comment by Mogli12** [comment]
Yes, it worked. Many thanks for the translation.
