### ISSUE TITLE
inching Gas/breaks

### ISSUE THREAD

**Issue by cabmac** [Mogli12/KeyboardSteer#28]
Hi, ich weiss, vielleicht noch ein bissl frueh fuer Anregungen, das noch keine docu gibt, aber vielleicht eine Anregung fuer Keboardsteer...ich glaube upsidedown hatte das im Drive-Control, da war eine kleine option um z.B. besser "sanft" bremsen zu koennen. Da drueckte man zusaetzlich zu "S" die Alt-Taste und da wurde die Bremskraft um 50% reduziert (ich weiss nicht mehr, obs genau 50 waren)...Bei STrassenfahrten oder sonstigen Arbeiten war das klasse, das man "2-Stufig" Bremsen konnte und auch mal sanft an eine Kruezung oder wo auch immer ranfarhen konnte....koennte man das implementieren?

Schoene Gruesse

Claudio

PS, faellt mir gerade ein, dieses "Inching" funkionierte auch beim Gasgeben , also W und Alt machte ein sanfteres Anfahren moeglich...

ups, ich seh grad, dass du das schon implementiert hast...war das in FS17 auch schon ?

bin ja beschuert...das war ja Keyboardsteer...und nicht drive-control....closed :(

**Comment by Mogli12** [comment]
Ja, in FS17 war es drin, aber in FS19 fehlt es noch.

**Comment by cabmac** [comment]
perfect 👌 👌 up to now... just miss "breakg-inching".. :)

bg
Claudio
