### ISSUE TITLE
Dedicated server

### ISSUE THREAD

**Issue by vone** [Mogli12/KeyboardSteer#29]
Trying to use it on a dedicated server, the tractor has brake lights on and will only move forward very slowly. The log shows what happens when i log into server, tab to a tractor and hit space (shuttle) [Server log](https://pastebin.com/iy9jXWDA) [Client log](https://pastebin.com/2XS7W1sh)

**Comment by Mogli12** [comment]
Ok, even in the MP coding Giants renamed essential classes. I fear we have to wait until the luadoc is published.

**Comment by modelleicher** [comment]
networkGetObject -> NetworkUtil.getObject
networkGetObjectId -> NetworkUtil.getObjectId

They've made utils and manager for everything

**Comment by Mogli12** [comment]
Yes, I saw it in the video from FarmCon 2018

**Comment by vone** [comment]
It's working now, but there is an error in the [client log](https://pastebin.com/wmH6FJae). No errors on the server.

I understand that we have to wait until giants release the lua doc. :) Thanks for the awsome work Stefan!

**Comment by vone** [comment]
Works great now! No errors in the log.

**Comment by Mogli12** [comment]
Thanks!
