### ISSUE TITLE
bucking indoor camera MP

### ISSUE THREAD

**Issue by Sheldon311** [Mogli12/KeyboardSteer#3]
Hello, I have a problem in MP-Mode, it jerky very in the Indoor Camera, when a second player is in the game. If he leaves the room, it works.
The Outdoor Camera functions normally.

Why jerky camera inside when more players are in the room?

**Comment by Mogli12** [comment]
Hi,
Does the problem sill occur with version 2.1 beta 2?
BR

**Comment by Mogli12** [comment]
Hi,
I hope it works in 2.1 beta 3? 
BR

**Comment by Sheldon311** [comment]
Hi,
yes it works in LS17!

**Comment by Mogli12** [comment]
Hi,

These are good news. Thans for testing. I think the next version will be the release version 2.1.

BR
