### ISSUE TITLE
Excessive camera movement when using shuttle outside vehicle

### ISSUE THREAD

**Issue by WrinkleysRule** [Mogli12/KeyboardSteer#32]
The switching back and forward of the camera when using the shuttle outside the vehicle is a bit disconcerting. I have done a quick fix by adding the following after line 521 in the lua

elseif  not self.spec_enterable.cameras[camIndex].isInside then
		return false

hoping you can do a more permanet fix

**Comment by Mogli12** [comment]
Please do not change any file inside FS19_KeyboardSteer.zip. You can simply place your copy of keyboardSteerMogliConfig.xml directly in the mods folder.

**Comment by WrinkleysRule** [comment]
Hi Stefan,
I am aware that the reverse camera can be disabled from the settungs menu or the config.xml but that method seems to disable it totally, what I was trying to do was retain the interior camera reverse look but stop the camera switching targets when in exterior view and that code seemed to be the only way of achieving the desired result.

Colin

Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by Jayshua83** [comment]
> Please do not change any file inside FS19_KeyboardSteer.zip. You can simply place your copy of keyboardSteerMogliConfig.xml directly in the mods folder.

Putting the keyboardSteerMogliConfig.xml directly in the mods folder causes a Dedi Sever error about a corrupted mod. It should go into the modsSettings folder! :)

Both of these mods already save their settings into the modSettings folder!!

https://www.modhoster.com/mods/vehiclefruit-hud
https://www.modhoster.com/mods/vehicleinspector--2

**Comment by Mogli12** [comment]
Please check #23 about modSettings.
