### ISSUE TITLE
nill value on settingsscreen

### ISSUE THREAD

**Issue by Div3rsion** [Mogli12/KeyboardSteer#33]
Hoi Stefan,

In the settingsscreen in game there is a nill text at the last option on the left. Which is the on/off toggle for activating the forward/reverse gear option with spacebar.
I would like to implement the Dutch translations for this option as well but don't know which labels to use for this.
Guess it is something to do with ksmSHUTTLE as that is also the only one not translated yet in keybindingsscreen also.
Please advice so I can adjust it.

Regards 
Rick

**Comment by Mogli12** [comment]
Hi Rick,

Please check version 0.0.0.7.

Thanks,
Stefan

**Comment by Div3rsion** [comment]
ok, thnx
