### ISSUE TITLE
Just a request

### ISSUE THREAD

**Issue by zoli10** [Mogli12/KeyboardSteer#36]
Dear Mogli, first of all, sorry for my english. I would like to ask some advice. I tried to make a simple "hydrostatic" script for combines, but it was impossible for me in FS19. My plan was, that the throttle of my joystick control the cruiseControl: if the throttle is 10%, the cruiseControl maxspeed is 10% etc. If the throttle is "-10%", the combine go automatic backward, and the cruiseControl maxspeed is 10%...I could do this in the previous version, but there are full darkness now.......I would be very grateful if you could help me.   zoli

**Comment by Mogli12** [comment]
Hi Zoli,
I think the cruise control speed is an axis. But the gearbox had a similar function. So it will come with the gearbox once the LUADOC is out.
Regards, Mogli
