### ISSUE TITLE
"Durchdrehen" im MP

### ISSUE THREAD

**Issue by oschuhm** [Mogli12/KeyboardSteer#4]
Hi,
wenn ich die Indoor Kamera im Multiplayer nutze, dann dreht sie permament durch.
Sobald ich nach rechts / links drehe ... dann fährt die Kamera in der jeweiligen Richtung im Kreis.
Gruß
Oliver

**Comment by oschuhm** [comment]
wenn ich was helfen kann und / oder testen meld dich einfach.
Gruß
Oliver

**Comment by eXtatic-GitHub** [comment]
Hallo, ich habe vermutlich das gleiche Problem und hänge mich mal hier dran.

# Problem:
Blickwinkel ändert sich kontinuierlich im MP. Im SP fuktioniert es einwandfrei.

# Problembeschreibung:
Der Blickwinkel ändert sich kontinuierlich nach rechts, wenn kein Lenkeinschlag erfolgt.
Mit dem Lenkeinschlag ändert sich die Geschwindigkeit in der der Blickwinkel verändert wird. 
Das führt selbst bei minimalem Lenkeinschlag dazu, dass sich der Blickwinkel permanent im Kreis dreht.
Auf dem Dedi kann ich das permanente drehen verhindern, indem ich im Cockpit sowie außerhalb des Fahrzeugs die Kamerabewegung aktiviere. 
Aber selbst dann ist es nicht so flüssig wie im SP. Die Kamera bewegt sich Ruckartig und nicht flüssig. 
Habe es auch schon ohne weitere Mods auf dem Dedi getestet, keine Veränderung. 

# Testumgebung:
PC mit Logitech G27 Lenkrad
G-Portal Gameserver

# Serverlog:

GIANTS Engine Runtime 7.0.0 (13620) 64bit (Build Date: Oct 26 2016)
Copyright (c) 2008-2016, GIANTS Software GmbH (giants-software.com), All Rights Reserved.
Copyright (c) 2003-2016, Christian Ammann and Stefan Geiger, All Rights Reserved.
Application: profile
Main System
  CPU: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
  Memory: 32644 MB
  OS: Windows NT 6.3 64-bit
Physics System
  Version: 5.9.5
  Thread(s): 2
Input System
  Keyboard disabled
  Mouse disabled
  Gamepad/Joystick disabled
  Force Feedback disabled
Sound System
  Driver: NULL
Render System
  Driver: NULL
  NullConsoleDevice initialized
Started 4 threads for threadpool 'Render threadpool'
Hardware Profile
  Level: Low (forced)
  View Distance Factor: 0.750000
  Shadow Quality: 0.000000 Size: 1 Filter-Size: 4
  Shader Quality: 0
  Skip Mipmaps: 1
  LOD Distance Factor: 0.750000
  Terrain LOD Distance Factor: 0.750000
  Terrain Normal Mapping: Yes
  Foliage View Distance Factor: 1.000000
  Foliage Density: 0.300000
  Volume Mesh Tessellation Factor: 1.500000
  Tyre Tracks Segments Factor: 0.500000
  Max. Number of Shadow Lights: 0
  Max. Number of Lights: 512
  Max. Number of Lights Per Cluster: 32
  MSAA: 0
Farming Simulator 17
  Version: 1.2.1.1 1.2.1RC3
  Available Languages: en
  Language: en
  Time: 2016-11-05 14:17:34
  Register configuration 'inputAttacherJoint'
  Register configuration 'attacherJoint'
  Register configuration 'frontloader'
  Register configuration 'motor'
  Register configuration 'baseColor'
  Register configuration 'wheel'
  Register configuration 'rimColor'
  Register configuration 'design'
  Register configuration 'designColor'
  Register configuration 'vehicleType'
Game vehicle types loaded
Load mod: FS17_brantnerDPW18000
Load mod: FS17_fendtHarvesterPackage
Load mod: FS17_ForRealModule01_CropDestruction
Load mod: FS17_ForRealModule02_TireDirt
Load mod: FS17_ForRealModule03_GroundResponse
Load mod: FS17_fortunaFTM200_6_0
Load mod: FS17_holmerPack
Load mod: FS17_itRunnerPack
Load mod: FS17_KeyboardSteer
Load mod: FS17_kroneBigXPack
Load mod: FS17_marshallBC32
Load mod: FS17_mengeleGarant5402
Load mod: FS17_newHollandLM742
Load mod: FS17_newHollandW170C
Load mod: FS17_placeableRefillStation
Load mod: FS17_real_clock
Load mod: ZZZ_driveControl
Load mod: ZZZ_fastForward
Load mod: ZZZ_GPS
Started network game (10823)
  Register vehicle type: FS17_holmerPack.augerWagon_foldable
  Register vehicle type: FS17_holmerPack.tractor_crabSteering
keyboardSteerMogli initialized
  Register vehicle type: FS17_mengeleGarant5402.MengeleGarant5402
  Register vehicle type: FS17_mengeleGarant5402.SilageAdditivesTank
  Register vehicle type: FS17_mengeleGarant5402.BuyableBlades
--- installing driveControl by upsidedown into Drivable and Steerable...
dataS/cameraPath01.i3d (0.08) ms
dataS/cameraPath02.i3d (0.12) ms
dataS/cameraPath03.i3d (0.07) ms
data/sky/skyUS_day_night.i3d (7.67) ms
data/sky/rain.i3d (0.60) ms
data/sky/hail.i3d (0.29) ms
data/sky/dust.i3d (0.23) ms
data/maps/map01.i3d (1220.66) ms
data/objects/basketball/basketball.i3d (1.02) ms
--- loading KeyboardSteer v2.0 by mogli ---
--- loading driveControl mod V4.03 (by upsidedown)---
--- fast Forward Mod V2.1 loaded --- (by upsidedown)
--- loading GPS mod V5.01 --- (by upsidedown)
Disabled withering
data/vehicles/trailers/metaltech/db8000.i3d (22.69) ms
data/vehicles/tools/kverneland/kvernelandExactaEL.i3d (14.04) ms
data/vehicles/steerable/newHolland/newHolland8340.i3d (28.80) ms
loading D:/home/sid_169618/farmingSim_2017/profile//driveControl_config.xml for driveControl-Mod configuration
driveControl module shuttle started
driveControl module fourWDandDifferentials not started
driveControl module cruiseControl not started
driveControl module showNearestFillLevel started
driveControl module pipeCam started
driveControl module implementControl started
driveControl module softGas not started
GPS mod inserted into Drivable Specialization (should happen only once!)
GPS mod inserted into Vehicle Camera (should happen only once!)
data/vehicles/tools/stoll/stollFrontLoaderFZ.i3d (3.55) ms
data/vehicles/tools/stoll/stollToolPalletFork.i3d (10.22) ms
data/vehicles/trailers/kroeger/kroegerTKD302.i3d (19.67) ms
data/vehicles/tools/vaderstad/vaderstadRapid600s.i3d (36.11) ms
data/vehicles/cutters/masseyFerguson/MFActivaHeader.i3d (20.13) ms
data/vehicles/steerable/masseyFerguson/MF7347Activa.i3d (39.18) ms
data/vehicles/steerable/caseIH/caseIH1455.i3d (38.40) ms
data/placeables/shelters/storageShelter01.i3d (4.05) ms
data/placeables/shelters/storageShelter02.i3d (2.85) ms
data/objects/bigBagContainer/bigBagContainerSeeds.i3d (2.34) ms
data/objects/pallets/fertilizerTank.i3d (1.92) ms
data/placeables/shelters/vehicleShelter.i3d (1.32) ms
data/vehicles/train/locomotive.i3d (16.99) ms
data/vehicles/train/wagonTimber.i3d (7.88) ms
data/vehicles/train/wagonWoodChips.i3d (9.57) ms
data/vehicles/train/wagonGrain.i3d (7.83) ms
data/vehicles/train/wagonSugarbeets.i3d (9.26) ms
dataS2/character/player/player01.i3d (258.46) ms

# Client Log:

GIANTS Engine Runtime 7.0.0 (13628) 64bit (Build Date: Oct 27 2016)
Copyright (c) 2008-2016, GIANTS Software GmbH (giants-software.com), All Rights Reserved.
Copyright (c) 2003-2016, Christian Ammann and Stefan Geiger, All Rights Reserved.
Application: FarmingSimulator2017
Main System
  CPU: Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
  Memory: 16328 MB
  OS: Windows NT 10.0 64-bit
Physics System
  Version: 5.9.5
  Thread(s): 2
Input System
  Keyboard enabled
  Mouse enabled
  Gamepad/Joystick enabled
  Force Feedback disabled
  Name: Logitech G27 Racing Wheel USB
Audio System
  Driver: OpenAL
  Version: 1.1
  Device: Generic Software
Render System
  Driver: Direct 3D 11
  Card Vendor: NVIDIA Corporation
  Renderer: NVIDIA GeForce GTX 970
  Revision: 161
  Feature level: DirectX 11 ON
Info: Effective window resolution 3840 x 2160
Started 4 threads for threadpool 'Render threadpool'
Hardware Profile
  Level: Very High (forced)
  View Distance Factor: 1.300000
  Shadow Quality: 2.000000 Size: 4096 Filter-Size: 16
  Shader Quality: 3
  Skip Mipmaps: 0
  LOD Distance Factor: 1.300000
  Terrain LOD Distance Factor: 2.000000
  Terrain Normal Mapping: Yes
  Foliage View Distance Factor: 1.600000
  Foliage Density: 0.500000
  Volume Mesh Tessellation Factor: 0.750000
  Tyre Tracks Segments Factor: 4.000000
  Max. Number of Shadow Lights: 5
  Max. Number of Lights: 512
  Max. Number of Lights Per Cluster: 32
  MSAA: 4
Head Tracking System
  Driver: TrackIR Client
  Version: 5.00
Farming Simulator 17
  Version: 1.2.1.1 1.2.1RC3
  Available Languages: en de jp pl cz fr es ru it pt hu nl cs ct br tr ro kr
  Language: de
  Time: 2016-11-05 18:03:20
  Register configuration 'inputAttacherJoint'
  Register configuration 'attacherJoint'
  Register configuration 'frontloader'
  Register configuration 'motor'
  Register configuration 'baseColor'
  Register configuration 'wheel'
  Register configuration 'rimColor'
  Register configuration 'design'
  Register configuration 'designColor'
  Register configuration 'vehicleType'
Game vehicle types loaded
Load mod: FS17_challengerMT700EFieldViper
Load mod: FS17_valtraTSeriesCowEdition
Load mod: FS17_brantnerDPW18000
Load mod: FS17_fendtHarvesterPackage
Load mod: FS17_flieglVFW10600
Load mod: FS17_ForRealModule02_TireDirt
Load mod: FS17_ForRealModule03_GroundResponse
Load mod: FS17_fortunaFTM200_6_0
Load mod: FS17_holmerPack
Load mod: FS17_itRunnerPack
Load mod: FS17_KeyboardSteer
Load mod: FS17_kroneBigXPack
Load mod: FS17_marshallBC32
Load mod: FS17_mengeleGarant5402
Load mod: FS17_newHollandLM742
Load mod: FS17_newHollandW170C
Load mod: FS17_placeableRefillStation
Load mod: FS17_real_clock
Load mod: FS17_veenhuisW400
Load mod: ZZZ_driveControl
Load mod: ZZZ_fastForward
Load mod: ZZZ_GPS
  Register vehicle type: FS17_holmerPack.augerWagon_foldable
  Register vehicle type: FS17_holmerPack.tractor_crabSteering
keyboardSteerMogli initialized
  Register vehicle type: FS17_mengeleGarant5402.MengeleGarant5402
  Register vehicle type: FS17_mengeleGarant5402.SilageAdditivesTank
  Register vehicle type: FS17_mengeleGarant5402.BuyableBlades
--- installing driveControl by upsidedown into Drivable and Steerable...
dataS/cameraPath01.i3d (0.15) ms
dataS/cameraPath02.i3d (0.13) ms
dataS/cameraPath03.i3d (0.08) ms
data/sky/skyUS_day_night.i3d (9.58) ms
data/sky/rain.i3d (1.44) ms
data/sky/hail.i3d (1.14) ms
data/sky/dust.i3d (0.72) ms
data/maps/map01.i3d (1732.48) ms
data/objects/basketball/basketball.i3d (1.87) ms
--- loading KeyboardSteer v2.0 by mogli ---
--- loading driveControl mod V4.03 (by upsidedown)---
--- fast Forward Mod V2.1 loaded --- (by upsidedown)
--- loading GPS mod V5.01 --- (by upsidedown)
Enabled withering
Joined network game (28)
data/vehicles/trailers/metaltech/db8000.i3d (33.56) ms
data/vehicles/tools/kverneland/kvernelandExactaEL.i3d (19.12) ms
data/vehicles/steerable/newHolland/newHolland8340.i3d (37.22) ms
loading C:/Users/eXtatic/Documents/My Games/FarmingSimulator2017//driveControl_config.xml for driveControl-Mod configuration
driveControl module shuttle started
driveControl module fourWDandDifferentials not started
driveControl module cruiseControl not started
driveControl module showNearestFillLevel started
driveControl module pipeCam started
driveControl module implementControl started
driveControl module softGas not started
GPS mod inserted into Drivable Specialization (should happen only once!)
GPS mod inserted into Vehicle Camera (should happen only once!)
data/vehicles/tools/stoll/stollFrontLoaderFZ.i3d (6.07) ms
data/vehicles/tools/stoll/stollToolPalletFork.i3d (12.66) ms
data/vehicles/trailers/kroeger/kroegerTKD302.i3d (26.63) ms
data/vehicles/tools/vaderstad/vaderstadRapid600s.i3d (42.92) ms
data/vehicles/cutters/masseyFerguson/MFActivaHeader.i3d (30.76) ms
data/vehicles/steerable/masseyFerguson/MF7347Activa.i3d (52.69) ms
data/vehicles/steerable/caseIH/caseIH1455.i3d (52.29) ms
dataS2/character/player/player01.i3d (447.55) ms
data/placeables/shelters/storageShelter01.i3d (6.70) ms
data/placeables/shelters/storageShelter02.i3d (2.98) ms
data/placeables/shelters/vehicleShelter.i3d (1.76) ms
data/vehicles/train/locomotive.i3d (24.75) ms
data/vehicles/train/wagonTimber.i3d (11.22) ms
data/vehicles/train/wagonWoodChips.i3d (12.72) ms
data/vehicles/train/wagonGrain.i3d (12.34) ms
data/vehicles/train/wagonSugarbeets.i3d (12.97) ms
Disabled withering
Error: FSBaseMission:setNumPickupObjects is only allowed on a server
thoma joined the game
Error: FSBaseMission:setNumPickupObjects is only allowed on a server
data/objects/pallets/fertilizerTank.i3d (3.00) ms
dataS2/character/pedestrians/woman03.i3d (90.35) ms
C:/Users/eXtatic/Documents/My Games/FarmingSimulator2017/mods/FS17_placeableRefillStation/seedRefillTank.i3d (48.95) ms
C:/Users/eXtatic/Documents/My Games/FarmingSimulator2017/mods/FS17_placeableRefillStation/fertilizerRefillTank.i3d (2.96) ms
dataS2/character/pedestrians/woman05.i3d (6.68) ms
Physics System
  Version: 5.9.5
  Thread(s): 2
Input System
  Keyboard enabled
  Mouse enabled
  Gamepad/Joystick enabled
  Force Feedback disabled
  Name: Logitech G27 Racing Wheel USB
Audio System
  Driver: OpenAL
  Version: 1.1
  Device: Generic Software
Render System
  Driver: Direct 3D 11
  Card Vendor: NVIDIA Corporation
  Renderer: NVIDIA GeForce GTX 970
  Revision: 161
  Feature level: DirectX 11 ON
Info: Effective window resolution 3840 x 2160
Started 4 threads for threadpool 'Render threadpool'
Hardware Profile
  Level: Very High (forced)
  View Distance Factor: 1.300000
  Shadow Quality: 2.000000 Size: 4096 Filter-Size: 16
  Shader Quality: 3
  Skip Mipmaps: 0
  LOD Distance Factor: 1.300000
  Terrain LOD Distance Factor: 2.000000
  Terrain Normal Mapping: Yes
  Foliage View Distance Factor: 1.600000
  Foliage Density: 0.500000
  Volume Mesh Tessellation Factor: 0.750000
  Tyre Tracks Segments Factor: 4.000000
  Max. Number of Shadow Lights: 5
  Max. Number of Lights: 512
  Max. Number of Lights Per Cluster: 32
  MSAA: 4
Head Tracking System
  Driver: TrackIR Client
  Version: 5.00
Farming Simulator 17
  Version: 1.2.1.1 1.2.1RC3
  Available Languages: en de jp pl cz fr es ru it pt hu nl cs ct br tr ro kr
  Language: de
  Time: 2016-11-05 19:54:51
  Register configuration 'inputAttacherJoint'
  Register configuration 'attacherJoint'
  Register configuration 'frontloader'
  Register configuration 'motor'
  Register configuration 'baseColor'
  Register configuration 'wheel'
  Register configuration 'rimColor'
  Register configuration 'design'
  Register configuration 'designColor'
  Register configuration 'vehicleType'
Game vehicle types loaded
Load mod: FS17_challengerMT700EFieldViper
Load mod: FS17_valtraTSeriesCowEdition
Load mod: FS17_brantnerDPW18000
Load mod: FS17_fendtHarvesterPackage
Load mod: FS17_flieglVFW10600
Load mod: FS17_ForRealModule02_TireDirt
Load mod: FS17_ForRealModule03_GroundResponse
Load mod: FS17_fortunaFTM200_6_0
Load mod: FS17_holmerPack
Load mod: FS17_itRunnerPack
Load mod: FS17_KeyboardSteer
Load mod: FS17_kroneBigXPack
Load mod: FS17_marshallBC32
Load mod: FS17_mengeleGarant5402
Load mod: FS17_newHollandLM742
Load mod: FS17_newHollandW170C
Load mod: FS17_placeableRefillStation
Load mod: FS17_real_clock
Load mod: FS17_veenhuisW400
Load mod: ZZZ_driveControl
Load mod: ZZZ_fastForward
Load mod: ZZZ_GPS

**Comment by Mogli12** [comment]
Hallo,

ich bin in Version 2.1 beta 2 nochmals für das MP-Coding gegangen. Aber leider komme ich heute nicht mehr zum Testen. Tritt das Problem damit immer noch auf?

Viele Grüße

**Comment by Mogli12** [comment]
Hallo,

Logs kannst Du besser in Gist hoch laden. Ist das Problem mit 2.1 Beta 3 gelöst?

Vielen Dank

**Comment by eXtatic-GitHub** [comment]
Hallo,, ich hatte dir über Modhoster eine Antwort geschrieben wo auch ein Video angehängt war.
Zitat:
"Vielen Dank für die Bemühungen, leider ist das Verhalten eher schlechter geworden. 
Es scheint als würde das Bild immer zwischen dem normalen Blick (geradeaus) und dem Lenkwinkelblick (seitlich) hin und her springen. Führt aktuell dazu, dass ich beim lenken zitternde Doppelbilder bekomme... 
Habe es auch ohne Lenkrad getestet, selbes Verhalten. Auch die Änderung von 4k auf Full HD hat nichts geändert. "

**Comment by Mogli12** [comment]
Hi eXtatic,

Deine Nachricht ist von Mittwoch, die Beta 3 ist aber von Gestern (Freitag) und ich habe heute noch die Beta 4 hochgeladen.

Viele Grüße

**Comment by eXtatic-GitHub** [comment]
Halllo Mogli12,

ich habe soeben die Beta 5 erfolgreich auf meinem Dedi-Server getestet!
Vielen Dank!
