### ISSUE TITLE
config save problem 

### ISSUE THREAD

**Issue by denut** [Mogli12/KeyboardSteer#40]
hello

i test your mod in solo there si a problem at save got lua error for solo game is working after the error 

but in multiplayer the server stucks

maybe the problem is writing the file : keyboardSteerMogliConfig.xml

if you will we can hel you with our servers 

come on our discord https://discord.gg/DfpQmKX ask nico or christophe_tel, chris_pc

we have a dedicated test server to work 

we are french but we can english an a little german 

tank's for you mods !!!

**Comment by Mogli12** [comment]
It should be fixed
