### ISSUE TITLE
lost power on combine

### ISSUE THREAD

**Issue by Div3rsion** [Mogli12/KeyboardSteer#45]
After update to 0.0.9 my son lost power on his combine.
He can not climb up the hill anymore.
Earlier this week with other versions no problem.
A Rostelmach on field 31 on Felsbrunn.
What is changed?

**Comment by Mogli12** [comment]
I do not know what changed. I propose to turn off shuttle control.

**Comment by Div3rsion** [comment]
ok

**Comment by Mogli12** [comment]
I hope it is fixed with v0.0.1.0. I increased the minimum RPM as well for combines.
