### ISSUE TITLE
keyboardSteerMogliConfig.xml has NO option for Shuttle Control

### ISSUE THREAD

**Issue by Jayshua83** [Mogli12/KeyboardSteer#47]
We need keyboardSteerMogliConfig.xml to have an option for Shuttle Control Off/False - On/True

My wife and I use this mod but ONLY use Adaptive Steering so I turn everything else off/false!

**Comment by Mogli12** [comment]
There is now the setting `<shuttleControl type="bool" value="false"/>` in the mod settings.
