### ISSUE TITLE
Wiki? Explanation for Throttle Control?

### ISSUE THREAD

**Issue by Jayshua83** [Mogli12/KeyboardSteer#48]
What does the Throttle Control do? Some explanation would be nice!

What is the difference between 80/100 and 100/80 ?

Thanks!

**Comment by DRiveByLEvoX** [comment]
The First value ist your "Max Forward speed" und the second is the "Max Backup speed" I have testet it a little.

**Comment by Mogli12** [comment]
Hi,

The first value is the value of the acceleration / brake pedal is LShift is not pressed. The second value is the same if LShift is pressed. It is only useful if you play with a keyboard. 

Regards,
Stefan
