### ISSUE TITLE
Feature Request: add options to look 45° left and right backwards

### ISSUE THREAD

**Issue by fdanapfel** [Mogli12/KeyboardSteer#51]
Using FS19_KeyboardSteer v0.0.1.0.

Currently when using the functions to look left and right the view always switches to 45° left and right looking forward.

It would be nice that when looking backwards when using the functions for looking left and right would also set the view to look backwards at 45° left and right instead of switching to the forward view.

**Comment by Mogli12** [comment]
Good idea!

**Comment by Mogli12** [comment]
The mod now looks left and right based on the current view direction.
