### ISSUE TITLE
F und R immer sichtbar

### ISSUE THREAD

**Issue by Einfllslos** [Mogli12/KeyboardSteer#52]
Dieses kleine F wenn man vowärts fährt oder das R wenn man rückwärts fährt im Hud unten rechts ist zwar cool, aber es bleibt auch sichtbar wenn ich z.B. in den Shop gehe. 
Also es verschwindet einfach nicht.
Könnte das dann ausgeblendet werden, wenn man den Shop öffnet?

**Comment by Mogli12** [comment]
Das sollte mit Version 0.0.1.2 gelöst sein.

**Comment by Einfllslos** [comment]
Jo
