### ISSUE TITLE
Feature Request: Key to switch forward/back view

### ISSUE THREAD

**Issue by chudya** [Mogli12/KeyboardSteer#55]
Can you add shortcut key to switch forward/back view (like fwd/back drive direction in shuttle)? It will be very helpfull to drive with steering wheel. Very often i drive back looking forward and drive forward looking back. Auto reverse camera is not enough in this case.    
Sorry, i don't speak english :D

**Comment by Mogli12** [comment]
Hi, You can assign ksmUP and ksmDOWN as you need it.
Regards,

**Comment by chudya** [comment]
I now that, but then i need to use three keys on wheel. It will be very convenient to use only two keys: one for drive direction, two for looking direction.    
If you can add this shortcut, you make me happy :)

**Comment by ivanlii** [comment]
Hi Mogli, indeed no need for 2 inputs for forward/back look, 1 switch is enough.

**Comment by Mogli12** [comment]
Please check if you activated the "Look Backwards" setting.

**Comment by ivanlii** [comment]
I dont use look backwards on all vehicles, it was about independent look vs driving direction.
Thanks

**Comment by Mogli12** [comment]
I tried to improve it a little. But it is not so easy.

**Comment by ivanlii** [comment]
>     1. when looking back (180 degrees), peak L/R are relative to the tractor, not drivers camera;

Hi Stefan, 
would you consider to check this?
I keep changing 0.7/03 and -0.7/-0.3 to -0.7/0.3 and 0.7/-0.3
Is weird when looking back and pressing peak/look left will turn camera to the right...

**Comment by Mogli12** [comment]
Project is stopped as it does not work together with sleep on Dedi server.
