### ISSUE TITLE
How To : Have same settings across all equipment?

### ISSUE THREAD

**Issue by Jayshua83** [Mogli12/KeyboardSteer#56]
How can I have a Global Settings across ALL equipment?

BTW this is a really useful Mod! My wife and I really love this and use it above almost all others! :)

**Comment by Jayshua83** [comment]
I just edited keyboardSteerMogliConfig.xml and dumped it back in the .zip for now. Works until modsSettings folder works...

**Comment by Mogli12** [comment]
You can place your own keyboardSteerMogliConfig.xml directly in the mods folder.

**Comment by Jayshua83** [comment]
Per what I said in #32 ...

Putting the keyboardSteerMogliConfig.xml directly in the mods folder causes a Dedicated Sever error about a corrupted mod. It should go into the modsSettings folder? :) Is that possible?

ALL of these mods already save their settings into the modsSettings folder!!

https://www.modhoster.com/mods/vehiclefruit-hud
https://www.modhoster.com/mods/vehicleinspector--2
https://www.modhoster.com/mods/enlarge-field-yield

**Comment by Mogli12** [comment]
Can you upload files in the modSettings folder?

**Comment by Jayshua83** [comment]
I am sorry, what? You want files from the other mods? They are just .xml files.

**Comment by Mogli12** [comment]
No, is it possible for you to upload a file in the modSettings folder of the dedi server? I did not order one.

**Comment by Jayshua83** [comment]
I would assume so? I am just running one on my own system.

**Comment by Jayshua83** [comment]
Doesn't appear your change is working?

Documents\My Games\FarmingSimulator2019\modsSettings\KeyboardSteer\keyboardSteerMogliConfig.xml is not loading...

hrmm

**Comment by Mogli12** [comment]
Why a sub folder? It is a single file, directly placed in modSettings:
...\Documents\My Games\FarmingSimulator2019\modsSettings\keyboardSteerMogliConfig.xml

**Comment by Jayshua83** [comment]
Oh ok. All the other mods saved into a separate sub-folder (not sure why) and thought this would too! Thought maybe it was the game doing that!

Thanks!

**Comment by Harag9** [comment]
> You can place your own keyboardSteerMogliConfig.xml directly in the mods folder.

So extract it out of the zip file, edit it and keep it in the same folder where all the zip files live? Thanks - I personally don't like the rotate camera feature and turn that off and was getting a pain to do in all the contracts. :) Loving the mod though.

**Comment by Mogli12** [comment]
Please check #23.
