### ISSUE TITLE
Feature Request: Key to toggle steering back (free steering)

### ISSUE THREAD

**Issue by AgroMeester** [Mogli12/KeyboardSteer#57]
Hi Stefan,

Would you be so kind to consider an option to toggle the "steering back speed" setting between "0" (off) and the last set preference speed. This wil result in a functionality much like the "free steering" mode in DriveControl. Thanks in advance!

Love your mods. Keep up the good work!

Greetings from Holland,

AgroMeester

**Comment by Mogli12** [comment]
Hi,

I think there is already a setting in the ingame menu.

Regards,
Stefan

**Comment by AgroMeester** [comment]
Hi Stefan,

Yes there is a "toggle steering mode" in the ingame menu but that relates to 2-wheel or 4-wheel steering (i.e. Kramer frontloader).
When I'm driving with the keyboard I like to switch between free-steering (steering back = off) for making smooth curves and then switch back so it will automatically center the steering again. I usually map it to the numpad "=" button so that when i'm driving with WASD I can instantly switch to free-steering with my right thumb. You get my idea? Please re-think this request again because I think it would fit you mod "Smoother steering with the key board" perfectly!

Regards,

AgroMeester

**Comment by AgroMeester** [comment]
Yes, in the esc menu you can change the steering back speed from 0 to whatever you prefer. BUT you can not map it to a key and drive like i described in the previous comment.

**Comment by AgroMeester** [comment]
OK Stefan,
I'll try to explain a little better.
When you're making a left turn you press the "A" button what like 8, 9, 10 times? And doing so you kind of "wiggle" through the curve, right?

With my driving method you approach the curve, press a button (with you right hand because your left hand is on the WASD keys) to enable free-steering. Then you press the "A" for a certain amount of time to steer into the curve and release the "A" key. Then you drive smoothly through the curve and at the end of the curve you press that mapped button again to enable "normal" keyboard steering and your tractor centers itself again and drive along in a straight line.

That means no more "wiggling" through curves and driving feels more or less like driving with a wheel! Great experience! I really recommend it.

Greetings,

AgroMeester

**Comment by AgroMeester** [comment]
Hi Stefan,

Did you read my last comment? If so I will assume that my suggestion is a definite "not interested in implementing". 

Thanks for a great mod anyways!

Greetings,

AgroMeester

**Comment by Mogli12** [comment]
Hi AgroMeester,

I did read your comment. But in FS19 I did not yet touch the autoRotateBack. This is one of the undocumented features. The complete spec. Steerable is missing.

Regards,
Stefan

**Comment by Mogli12** [comment]
You can assign action binding ksmNO_ARB to whatever key you like. I tried to assign it to RAlt but it did not work.

**Comment by AgroMeester** [comment]
Hi Stefan,

Just tried it and it works like a charm! Thank you so much for implementing this feature.
I think it even works better than the Free-Steering from DriveControl because you made the option activate while holding down the mapped key and deactivate when released. This takes a little getting used to but I'm happy so far! 

Greetings,

AgroMeester

**Comment by Klifords** [comment]
I would also like a feature like the one from drive controll in FS17, I used it all the time when running forestry equipment and it's very helpful, and actually how steering works on such machines in real life.
