### ISSUE TITLE
Feature Request: "Peek" left and right

### ISSUE THREAD

**Issue by fdanapfel** [Mogli12/KeyboardSteer#58]
Currently when selecting to look left or right the view stays like this until another viewing direction is chosen.

Since most of the time you only look left or right for a short amount of time when operating a machine (for example to check the mirror or to verify that the edge of a machine is where it is supposed to be) it would be nice to have an option to choose to just look left or right as long as the key/button for that view direction is pressed, and when the button is released the view automatically changes back to the previous viewing direction.

**Comment by Mogli12** [comment]
Hi,
I have no idea how this kind of "as long as key is pressed" should work with the new concept of action bindings in FS19. Additionally, I do not see any free key for that purpose.
Regards,
Stefan

**Comment by fdanapfel** [comment]
Might be worth asking the developers from Giants directly if this is possible with the new concept in FS19.

In order to avoid having to assign additional keys maybe it would be possible to make it a switchable option, so that users can choose if they only want to "peek" or keep the view permanently switched.

**Comment by Mogli12** [comment]
Does anybody have contact to Giants? I do not have such contact.

**Comment by cabmac** [comment]
from my experience..  STEGEI until now always responded to my PMs...

**Comment by Mogli12** [comment]
It works with version v0.0.1.3

**Comment by fdanapfel** [comment]
Just tried v0.0.1.3, and it indeed works as I imagined it.

Cool!!! Many, many thanks!!!
