### ISSUE TITLE
V 2.0.1.2

### ISSUE THREAD

**Issue by cabmac** [Mogli12/KeyboardSteer#6]
Moin, mit der letzten Version ist die original "Fahrzeugkamara zuruecksetzen"-Funktion im LS-Menue ausser kraft gesetzt. D.h. beim Umschalten von Aussen- auf Innenkamara schwenkt diese wieder zum Ausgangspunkt, also als wenn das im Menue eingeschaltet waere.

LG, Claudio

**Comment by Mogli12** [comment]
Ja, es gibt da ein paar Problem, vor allem im MP. Anscheinend war die Beta 2 da nicht so gut.

**Comment by Mogli12** [comment]
Ist die Beta 3 jetzt besser?
