### ISSUE TITLE
Probleme mit Vierradantrieb und Shuttle Control

### ISSUE THREAD

**Issue by RuppMartin001** [Mogli12/KeyboardSteer#62]
Hallo Stefan,

ich finde es super, dass es nun eine Möglichkeit im LS19 gibt die Fahrtrichtung per Tastendruck zu ändern.
Vielen Dank dafür!
Darauf habe ich als Pedalfahrer schon lange gewartet.

Leider gibt es ab und zu ein Problem mit Version 0.0.1.4.
Wenn die Reifen des Traktors durchdrehen schaltet der Traktor auf Vierradantrieb.
Dann ist es mir schon öfters passiert, dass die eine Achse in die eine Richtung und die andere Achse in die andere Richtung dreht.

VIele Grüße

Martin

**Comment by Mogli12** [comment]
Hallo Martin,

das ist sicher kein Bug in KeyboardSteer. Der Mod nutzt Teile der normalen Rückfahreinrichtung, die bei den meisten Fahrzeugen zwar vorhanden, aber nicht einschaltbar ist.

Probiere mal, ob das Problem auch ohne KeyboardSteer aber mit Rückfahreinrichtung passiert.

Viele Grüße,
Stefan

**Comment by Mogli12** [comment]
Hallo Martin,

besser kann man Shuttle Control beim derzeitigen Stand der LUADOC nicht machen. Wenn es Dir nicht gefällt, dann musst Du wohl ganz ohne Shuttle Control spielen. Im Video ist a) zu viel Last im Frontlader und b) drehen die Hinterräder durch.

Viele Grüße,
Stefan
