### ISSUE TITLE
Feature Request: enable/disable snap angle with the same button

### ISSUE THREAD

**Issue by JanCraymer** [Mogli12/KeyboardSteer#63]
Hey Mogli,

first of all thanks for this great mod!

I just found out about the new snap angle feature and was eager to test it out. I'm using a steering wheel and assigned the feature to a steering wheel button. It would be a great enhancement if it could be turned off with pressing the same button again. I know it turns off if you steer hard enough but that is not practicable if you just want a small course correction.

Thanks,
Jan

**Comment by Mogli12** [comment]
Hi Jan,

This is a good idea.

Regards,
Stefan

**Comment by JanCraymer** [comment]
Wow, thanks for the fast response. Works like a charm.
