### ISSUE TITLE
ksm_help_1

### ISSUE THREAD

**Issue by Jayshua83** [Mogli12/KeyboardSteer#65]
> This Script varies the steering speed, the steering back speed and the maximum steering angle  depending on the current vehicle speed.
> In addition the camera is rotated according to the steering angle an the driving direction. The digital accelerator (**keys a and w**) can be limited.
> Only when Shift-Left is pressed at the same time 100% acceleration or braking happens.

Shouldn't that say **keys W and S**? Foward and Reverse/Brake? Or am I misunderstanding?

**Comment by Mogli12** [comment]
I reworked the texts. Thanks
