### ISSUE TITLE
Error: Running LUA method 'update'.

### ISSUE THREAD

**Issue by zed636** [Mogli12/KeyboardSteer#7]
Hi Mogli, I find this error using KeyboardSteer v 2.0.1.3 while I switch for Stepa trailer to other tractor using TAB button:
Error: Running LUA method 'update'.
C:/Users/Raziel/Documents/My Games/FarmingSimulator2017/mods/FS17_KeyboardSteer/keyboardSteerMogli.lua:222: attempt to perform arithmetic on field 'reverserDirection' (a nil value)
I try to update Farming Simulator 17 to version: 1.3.0.0 1.3RC4 but it give me the same error
Thank for your mods!
Zed636

**Comment by Mogli12** [comment]
Hi Zed636,
It is fixed with 2.1.0.4.
Regards, Stefan
