### ISSUE TITLE
Ultrawide monitor

### ISSUE THREAD

**Issue by Klifords** [Mogli12/KeyboardSteer#70]
I'm using an ultrawide monitor with aspect ratio 32:9, and it seems the menu doesen't work as it should at this ratio, and the F and R letters for forward and reveres for the shuttel isn't where it's supposed to be on the monitor, it's kinda inside the speedomeeter, just below the durability meeter.
https://imgur.com/a/LmHcUQT

**Comment by Mogli12** [comment]
It should be fixed in the latest version

**Comment by Klifords** [comment]
Thanks, the F and R are good now, however the menu is still a bit off.
https://imgur.com/a/ON2wPsG

**Comment by Mogli12** [comment]
Project is stopped as it does not work together with sleep on Dedi server.
