### ISSUE TITLE
Drescher will nur vorwärts fahren

### ISSUE THREAD

**Issue by Amadeo01** [Mogli12/KeyboardSteer#71]
Stefan, dir ein besinnliches Weihnachtsfest.

Ich habe  beim Drescher ein Problem mit der Umschalttaste. 
- Komme ich ins Spiel dann funktioniert das Vor- u. Rückwärtsfahren mit Umschalttaste.
- Bin ich aber im Spiel und nutze den Drescher erneut, dann funktioniert die Umschalttaste NICHT mehr. Der Drescher "überlegt" eine Millisekunde (mit kurzem Ruckeln nach hinten), ob er gefordertes Rückwärtsfahren machen soll, fährt dann aber immer wieder NUR vorwärts.

Mache ich etwas falsch?

**Comment by Mogli12** [comment]
Um welches Modell handelt es sich. Eventuell muss man nach dem Umschalten der Fahrtrichtung nochmals ein paar Sekunden bremsen.

**Comment by Amadeo01** [comment]
Ich wünsche dir ein frohes neues Jahr!

Besten Dank für deine Antwort.
Ich spiele mit dem Gamepad und nach dem Umschalten (Taste Y) fährt der Drescher mit Drücken der Bremstaste (linke Schultertaste = Bremstaste beim Traktor) sofort rückwärts. Bremsen und danach Stillstand ist so nur schwer möglich; er ist quasi immer in Bewegung (vor und zurück etc.). Er fährt jeweils nur mit den beiden Schulter-Tasten, ignoriert dabei immer die Taste Y. 

Die beiden Drescher sind Mods:
- FS19_John_Deere_S790_VE_Pack
- F19_ClaasLexion795

Vielleicht gibt es doch noch eine Lösung?

**Comment by Mogli12** [comment]
Es klingt so, als ob hier Shuttle Control ausgeschaltet ist. Schau doch mal in den Settings (StrgLinks + C) nach.

**Comment by Amadeo01** [comment]
Ach nein Stefan. Ich habe alle denkbaren Einstellungen ausprobiert. ---> Nix hilft ... leider.
Ich vermute jetzt, dass irgendeine Mod die Schuldige ist. Heute wollte sogar der Traktor mit der neuesten Version nicht mehr fahren. Beim Betätigen der Vorwärtstaste schaltete es sofort von F auf R und er bewegte sich gar nicht mehr.

**Comment by Mogli12** [comment]
Ich denke nicht, dass Du die Umschalttaste verwenden kannst. Probiere doch die Standardtastenbelegung.
