### ISSUE TITLE
Fehlermeldungen in der log.txt / Fahrzeuge wechseln

### ISSUE THREAD

**Issue by iljarogoff** [Mogli12/KeyboardSteer#72]
Bekomme im log immer folgende Fehlermeldung

`2018-12-25 09:06 Error: Running LUA method 'update'.
2018-12-25 09:06 C:/Users/ilja/Documents/My Games/FarmingSimulator2019/mods/FS19_KeyboardSteer/keyboardSteerMogli.lua:271: attempt to index a nil value`
Ich kann dann erstmal nicht mehr die Fahrzeuge switchen mit "TAB", muss erst aus- und wieder einsteigen, dann gehts wieder ne Weile.

**Comment by Mogli12** [comment]
Das sollte in der aktuellen Version gelöst sein. Aber ich denke, dass bei Deiner Installation irgendwas anders ist. Hast Du auch Patch 1.2 (Version 1.2.0.1) installiert?

**Comment by iljarogoff** [comment]
Ja, aktueller Patch. Danke schonmal für den Fix, bislang ist es nicht mehr passiert

**Comment by DLH007** [comment]
Ich hatte den Fehler auch schon mal, aus der Erinnerung kann ich folgendes sagen.
Traktor + Hänger + Jenz Häcksler
Beim switchen durch die Fahrzeuge geht es irgendwann nach dem Zufallsprinzip nicht mehr. Wenn man vor oder zurückswitcht geht es mal länger mal kürzer. Jedesmal entsteht ein Fehlereintrag in der Log.

Hängt man den Jenz Häcksler ab, ist der Fehler weg. Er war bis heute nicht reproduzierbar.

**Comment by Mogli12** [comment]
Ich denke, dass #104 dasselbe Problem beschreibt.
