### ISSUE TITLE
In der PDA/Map keine Tastatureingabe möglich

### ISSUE THREAD

**Issue by iljarogoff** [Mogli12/KeyboardSteer#73]
Manchmal kann ich, wenn ich die PDA mit "ESC" aktiviere, nicht mehr navigieren (mit der Maus), also die Tabs durchschalten, komme auch nicht mehr mit "ESC" raus. Muss dann in der Mapübersicht ein Fahrzeug finden und dann einsteigen, erst dann kann ich den PDA schliessen.
Evtl. ist die folgende Fehlermeldung im Log ein Indiz:
`2018-12-25 09:06 Error: Running LUA method 'update'.
2018-12-25 09:06 dataS/scripts/input/InputBinding.lua(3296) : bad argument #1 to 'pairs' (table expected, got nil)`

**Comment by Mogli12** [comment]
Was hat das mit keyboardSteer zu tun?

**Comment by iljarogoff** [comment]
Da dies erst auftritt, seit ich KeyboardSteer installiert habe, gehe ich davon aus, dass es damit zu tun hat. Wissen tu ich es natürlich nicht.

**Comment by Mogli12** [comment]
Wie Du [hier](https://gdn.giants-software.com/documentation_scripting_fs19.php?version=script&category=1&class=7052) sehen kannst, veröffentlicht Giants nicht das Coding von InputBinding.lua. Daher kann ich nicht sagen, was in Zeile 3296 schief läuft.
