### ISSUE TITLE
Multiplayer Bremslichter 

### ISSUE THREAD

**Issue by AGSAndreas** [Mogli12/KeyboardSteer#74]
Hallo, Stefan,
im SP leuchten die Bremslichter nur beim bremsen wie es sein soll.
Im MP leuchten die Bremslichter sofort wenn man vom Gas geht. 
Die Bremslichter leuchten immer außer man gibt Gas.

Gruß Andreas

**Comment by ZeeArts** [comment]
> im SP leuchten die Bremslichter nur beim bremsen wie es sein soll.
> Im MP leuchten die Bremslichter sofort wenn man vom Gas geht.
> Die Bremslichter leuchten immer außer man gibt Gas.

Hallo Stefan.
Kann ich bestätigen. Im SP alles top. MP wie beschrieben.

Gruß Stefan :D

**Comment by AGSAndreas** [comment]
Hallo Stefan,
in der Version 0.0.2.4 besteht das Problem leider immer noch.

Gruß Andreas

**Comment by wjschaap** [comment]
Hallo,
Ich habe mit version 0.0.2.4 das Problem nicht im MP spiel, aber leider immer noch im spiel auf unsere dedicated server.

Gruß Wieger Jan

**Comment by ZeeArts** [comment]
Jepp. Hier auch weiterhin auf dem Dedi-Server.

Gruß Stefan

**Comment by DRiveByLEvoX** [comment]
Das Problem besteht aber nur wenn man "Stop-and-Bremsung" und Shuttlecontrol aktiviert ist und allen anderen Kombinationen funktioniert es normal

**Comment by AGSAndreas** [comment]
> Das Problem besteht aber nur, wenn man "Stop-and-Bremsung" und alle anderen Kombinationen funktioniert

Das Problem besteht auf dem Dedi Server egal ob Stop ans Go Bremsung an ist oder nicht,
Gruß Andreas

**Comment by ZeeArts** [comment]
Habe eben die v0.0.2.5 getestet. Im SP (selbstgehosteten MP nicht getestet) funkioniert es wie es soll. Auf dem Dedi-Server bleiben die Bremslichter weiterhin an wenn man das Gas nicht betätigt.
Zudem ist mir etwas bei v0.0.2.4 aufgefallen (was ich bei der v0.0.2.5 auf die Schnelle nicht testen konnte): Als ich mit dem Ropa Panther 2 rückwärts gefahren bin und während des Ausrollens (ohne Zugabe von Gas) in den Vorwärtsgang geschaltet, und dann Gas gegeben habe, hat er die Rückwärtsrichtung beibehalten (obwohl die Ganganzeige "F" angezeigt hat) und beschleunigt. Auch die Bremse hat erst wieder reagiert, wenn man während des Rückwärtsrollens wieder in den Rückwärtsgang geschaltet hat. Man musste immer erst richtig stehen bleiben damit der Richtungswechsel angenommen wurde.

Großes Lob an Dich. Weiter so!
Gruß Stefan

**Comment by DLH007** [comment]
Ist mit v0.0.2.6 aufm Dedi noch immer so.

**Comment by AGSAndreas** [comment]
Ist mit v0.0.2.7 aufm Dedi noch immer so.

**Comment by Mogli12** [comment]
Es wird sich auch wohl nicht ändern. Ich habe keine Ahnung, warum es auf dem Dedi nicht funktioniert.

**Comment by Mogli12** [comment]
#127
