### ISSUE TITLE
Feature request: Visualisierung Arbeitsbreite

### ISSUE THREAD

**Issue by iljarogoff** [Mogli12/KeyboardSteer#75]
Ich hätte einen Vorschlag, weiß nicht ob das schwer zu implementieren ist. Nachdem der Mod bereits einen Spurhalteassistenten hat, wäre es möglich, eine Visualisierung einzubauen, um die Arbeitsbreite von Maschinen zu sehen, bspw. mit Linien, ähnlich wie beim GPSMod?
Im übrigen ein toller und wertvoller Mod, danke vielmals!

**Comment by Mogli12** [comment]
Hallo,

da bin ich eher dagegen. Mich hatte es in der Vergangenheit gestört, dass man mit der Tastatur ohne GPS kaum ein Feld ordentlich bearbeiten konnte. Aber entsprechende Traktoren (Deutz 6.81) hatten noch gar kein GPS. Die Rastersteuerung ist jetzt mein persönlicher Kompromiss. Am Vorgewende muss man alles selber machen. In der Reihe kann de Traktor dann aber ordentlich geradeaus fahren, was mir halt im Landwirtschafssimulator viel schwerer viel als in der Realität.

Viele Grüße
