### ISSUE TITLE
Doppelte Richtungsanzeige in der HUD

### ISSUE THREAD

**Issue by iljarogoff** [Mogli12/KeyboardSteer#76]
In der HUD unten rechts, habe ich plötzlich die Richtungsanzeige doppelt
![fsscreen_2018_12_26_16_52_49](https://user-images.githubusercontent.com/21023840/50450526-f54b2900-092e-11e9-87de-82ff719ed8bc.png)

**Comment by Mogli12** [comment]
Ja, die obere Anzeige ist nur bei "snap angle" aktiv und zeigt die Wunschrichtung an. Die untere Anzeige ist die aktuelle Richtung, also Kompass.

**Comment by iljarogoff** [comment]
Dann ist das jetzt mit der 0.0.2.4 neu dazu gekommen? In der 0.0.2.3 war das noch nicht. Danke für die Info, gute Idee  👍
