### ISSUE TITLE
Multilanguage issue (Dutch) ingame with keyboardsteer settings

### ISSUE THREAD

**Issue by PitbullSpirit** [Mogli12/KeyboardSteer#80]
As title says,

I use Dutch language and with the settings menu open I am  
not seeing Snap Angle, but nil
not seeing Camera Peek but nil
and next to Camera Peek it also says nil but there is nothing there as screen shows.

Screen shows what I see and dont see in settings in my own language which is Dutch
![fsscreen_2018_12_27_12_11_27](https://user-images.githubusercontent.com/22746021/50478473-97bbe880-09d1-11e9-99f0-463e5120f755.png)

It is not gamebreaking but it is kinda hard to know what options it are to adjust.
Hopefully it will be later on in one of the updates changed so it has better multilanguage support.

Other then that only noticed when using Snap, it has the habit to always go to same side and goes 0,1-0,5degrees off. Not annoying and might be reality anyways.

**Comment by PitbullSpirit** [comment]
It is better now, still not fully as you most likely want but at least nil is gone.

![fsscreen_2018_12_29_00_39_51](https://user-images.githubusercontent.com/22746021/50530883-8d4d3c00-0b02-11e9-832b-fc976d487fa1.png)

Also it gives this error in log for modDesc_l10n_nl.xml
Warning: Missing l10n 'input_ksmSNAP'
  Warning: Missing l10n 'input_ksmNO_ARB'
  Warning: Missing l10n 'input_ksmINCHING'

Thx for improving the mod step by step.

**Comment by Mogli12** [comment]
Hi, warnings are not errors!

**Comment by PitbullSpirit** [comment]
Thx for the Dutch translation update, it looks a lot better and i can understand what option does what. 
Thx Mogli and Happy New Year

**Comment by Mogli12** [comment]
Please thank @Div3rsion: #86
