### ISSUE TITLE
Keyboardsteer und Radlader

### ISSUE THREAD

**Issue by cabmac** [Mogli12/KeyboardSteer#81]
Hi, mit den Radladern scheint irgendwas nicht zu stimmen. Wenn man geradeaus faehrt, geht die "Wendeschaltung" vorwaerts/rueckwaerts, sobald man aber einlenkt, reagiert das shuttlecontrol nicht:

https://vimeo.com/manage/308406167/general

**Comment by Mogli12** [comment]
Hi,

bei Knicklenkern muss man anscheinend bis zum Stillstand abbremsen. Keine Ahnung woran das liegen kann.

Viele Grüße,

**Comment by DLH007** [comment]
Funktioniert mit 0.0.2.6 :)
