### ISSUE TITLE
Kameraschwenk, bei Rückfahreinrichtung

### ISSUE THREAD

**Issue by Babene03** [Mogli12/KeyboardSteer#84]
Hi, bei Traktoren, die eine Rückfahreinrichtung haben und man diese Aktiviert, schaut er in die entgegen Gesetze Richtung.

**Comment by Mogli12** [comment]
Bei welchem Gerät passiert das?

**Comment by Babene03** [comment]
bei der  Valtra TSeries, ist es uns aufgefallen

Wenn man die Rückfahreinrichtung nutzt, schaut er weiter nach vorne aus dem Traktor und nicht wie eigentlich, nach hinten, fährt man rückwärts schaut der nach hinten und nicht nach vorne.

**Comment by Mogli12** [comment]
Project is stopped as it does not work together with sleep on Dedi server.
