### ISSUE TITLE
Shuttle control animations

### ISSUE THREAD

**Issue by knuuud** [Mogli12/KeyboardSteer#85]
When using shuttle control the animations for reverse is not working. Shift leaver is not moving and when backing up the farmer is pressing the brake pedal instead of trottle.

**Comment by Mogli12** [comment]
Please check version 0.0.2.7

**Comment by knuuud** [comment]
0.0.2.7 seems to have fixed it :) good job! 😊

**Comment by Mogli12** [comment]
Thanks
