### ISSUE TITLE
Komisches Bremsen

### ISSUE THREAD

**Issue by Einfllslos** [Mogli12/KeyboardSteer#89]
Spiele mit Lenkrad und Pedalen.
Seit Version 2.7 hab ich ein Problem mit dem Bremsen beim kleinen Rostselmash Drescher.
Wenn ich bremse fängt ab ca. 4 km/h (wenn man von 20-5 km/h runter bremst) der Zeiger für die Geschwindigkeit an zu wackeln und der Drescher bremst nur noch sehr sehr langsam ab 4km/h.
Wenn ich eine Vollbremsung mache also die Bremse voll trete das gleiche.
Ab 4km/h bremst er nicht mehr so stark wie vorher auch wenn ich das Pedal nicht fester oder leichter trete. 
Das ganze geht dann bis 2 km/h so und dann bleibt er stehen. 
Ob der Drescher an oder ausgeschaltet ist hat soweit ich erkennen kann keine Auswirkung.

**Comment by Einfllslos** [comment]
Achso ja was ich vergessen hab.
Wenn ich den Drescher "ausrollen lasse" also nicht selbst bremse dann ist alles normal.

**Comment by Mogli12** [comment]
Welcher Drescher?

**Comment by Einfllslos** [comment]
Na der kleine Rostselmash aus dem Spiel.
Gibt ja nur zwei und davon der kleine.
Rostselmash Nova heißt der.

**Comment by Mogli12** [comment]
Tritt es in VCA immer noch auf?

**Comment by Mogli12** [comment]
Project is stopped as it does not work together with sleep on Dedi server.
