### ISSUE TITLE
Mod / Skript deaktivieren 

### ISSUE THREAD

**Issue by manfahrer** [Mogli12/KeyboardSteer#90]
Hallo, 
ist es möglich eine Funktion zu integrieren das der Mod aktiviert und deaktiviert werden kann für den Dedi Server ist es von Vorteil wenn mehrere Spieler das Skript nicht nutzen möchten. Es werden auch die Einstellungen für die Fahrzeuge nicht gespeichert. 

Wäre es auch möglich Suttle Contol als Standart aus ...
Danke für die Unterstützung.

**Comment by DLH007** [comment]
Unter "My Games\FarmingSimulator2019\modsSettings\" kann sich jeder eine "keyboardSteerMogliConfig.xml" anlegen und nach belieben einstellen, somit hat jeder seine persönliche Konfiguration. Damit man die Datei nicht selber schreiben muss, kann man sich diese aus der ZIP des Mods rausholen.

**Comment by ZeeArts** [comment]
> 
> 
> Unter **"My Games\FarmingSimulator2019\modsSettings"** kann sich jeder eine **keyboardSteerMogliConfig.xml** anlegen und nach belieben einstellen, somit hat jeder seine persönliche Konfiguration. Damit man die Datei nicht selber schreiben muss, kann man sich diese aus der ZIP des Mods rausholen.

Hmm. Ich habe es eben versucht mit einer individuellen xml. Es greifen noch immer die globalen Einstellungen. Muss die xml in einen eigenen Ordner im modsSettings?

Grüße Stefan

**Comment by DLH007** [comment]
Nein direkt in den modsSettings Ordner, nutze doch mal meine.
[keyboardSteerMogliConfig.zip](https://github.com/Mogli12/KeyboardSteer/files/2717698/keyboardSteerMogliConfig.zip)

**Comment by DLH007** [comment]
Hat es nun geklappt?

**Comment by Einfllslos** [comment]
Hab mal ne Frage dazu.
Ich finde keinen "modsSettings" Ordner. Muss ich den erst selbst erstellen?

**Comment by DLH007** [comment]
Den kannst du problemlos selbst erstellen. Bei mir war er da, vermutlich durch einen Mod der ihn erstellt hat. Er muss sich natürlich am richtigen Ort befinden, eine Ebene höher als der Mod Ordner.

**Comment by ZeeArts** [comment]
> 
> 
> Hat es nun geklappt?

Leider nein. Haben es mit 2 Leuten auf dem Server ausprobiert (mit unterschiedlichen Individualeinstellungen). Habe es sowohl mit Deiner, als auch mit meiner eigenen erstellten xml versucht. Evtl. liegt es daran, dass ich wieder zurück bin auf 0.0.2.6. Oder sollte es mit der Version auch schon funktionieren?

**Comment by DLH007** [comment]
Dann machst du irgendwas falsch, es hat schon vor der 2.6 funktioniert, war also schon länger eingebaut die Funktion.

**Comment by ZeeArts** [comment]
Mir ist etwas aufgefallen. Wenn ich in die Fahrzeuge einsteige, dann sind meine Einstellungen tatsächlich so wie ich sie in der xml festgelegt habe. Mir wird die Anzeige für Gang vor und zurück angezeigt. Sie zeigt auch an wenn ich umschalte. Allerdings funktioniert nur die Ganganzeige. Geschaltet wird nicht (komischerweise gehen auch die Lichter für den Rückwärtsgang dabei an und aus). Aber ich muss weiterhin auf die Bremse treten (Lenkrad mit Padalen) bzw. S drücken um Rückwärts zu fahren. Erst wenn ich mit Strg+c "Shuttle Control" deaktiviere, speichere, es wieder aktiviere und speichere, funktioniert die Schaltung für vor und zurück. Man kann übrigens direkt beim betreten des Fahrzeugs sehen (zumindest auf dem Dedi) ob Shuttle Control eingeschaltet ist, da hierbei die Bremslichter immer an sind wenn man kein Gas gibt.
Ich habe jetzt nochmal nachgeschaut. So sieht es bei mir aus (konnte jetzt im Vergleich zu Deinem Scrrenshot keinen Unterschied ausmachen):

https://www.img-load.de/images/2019/01/01/kbsteer.png

Gruß Stefan

**Comment by DLH007** [comment]
> Allerdings funktioniert nur die Ganganzeige. Geschaltet wird nicht (komischerweise gehen auch die Lichter für den Rückwärtsgang dabei an und aus). Aber ich muss weiterhin auf die Bremse treten (Lenkrad mit Padalen) bzw. S drücken um Rückwärts zu fahren. Erst wenn ich mit Strg+c "Shuttle Control" deaktiviere, speichere, es wieder aktiviere und speichere, funktioniert die Schaltung für vor und zurück.

Das ist vollkommen normal, dieses Verhalten tritt auf, wenn vor dir jmd. Shuttle-Control ausgeschalten hat.

**Comment by ZeeArts** [comment]
Im Singleplayer funktioniert es in der Tat einwandfrei (auch ohne dauerhaft leuchtenden Bremslichter).
Wenn das so gewollt ist, bzw. es normal ist, will ich nichts gesagt haben. :)
Hatte mich halt nur gewundert dass Shuttle Control jedes Mal nicht funktioniert hat, sobald einer der anderen Spieler ohne Shuttle vor mir das Fahrzeug benutzt hat.

**Comment by Mogli12** [comment]
Project is stopped as it does not work together with sleep on Dedi server.
