### ISSUE TITLE
Tempomat funktioniert nicht richtig 0.0.2.7

### ISSUE THREAD

**Issue by ZeeArts** [Mogli12/KeyboardSteer#91]
Hallo.
Ich habe seit der letzten Version bei einigen Fahrzeugen (unter anderem bei dem Case Quadtrac 620) das Problem dass der Tempomat die gewählte Einstellung ignoriert. Bei einigen Fahrzeugen funktioniert er nur teilweise (will man 10km/h fahren, muss man auf 14-15km/h einstellen). Das Problem war bei allen Spielern auf dem Dedi.
Bin erstmal wieder zurück auf 0.0.2.6. Dort funktioniert der Tempomat wieder wie er soll.

Grüße Stefan

**Comment by Einfllslos** [comment]
Hab das Problem auch. Zuerst dachte ich es liegt vielleicht am Gasbegrenzer, weil der sich ja auch dann verändert aber scheint mir nicht so.

**Comment by DLH007** [comment]
Mir ist es auch aufgefallen mit der 0.0.2.6, beim JCB Traktor mit Allradlenkung. Jedoch hatte ich bis zu eurem Text nicht als Fehler wahrgenommen.

**Comment by Mogli12** [comment]
Tritt das Problem in der aktuellen Version noch auf?

**Comment by Mogli12** [comment]
Project is stopped as it does not work together with sleep on Dedi server.
