### ISSUE TITLE
Spurhalteassistent ungenau auf Hanglagen

### ISSUE THREAD

**Issue by iljarogoff** [Mogli12/KeyboardSteer#92]
Hallo!
Mir ist aufgefallen, dass der Spurhalteassistent (snap angle) auf Schrägen und Hanglagen abweicht. Je steiler der Hang, umso größer wird die Abweichung. Auf der Ebene funktioniert er einwandfrei.
![fsscreen_2018_12_31_09_40_08](https://user-images.githubusercontent.com/21023840/50556972-82500280-0ce0-11e9-8599-7c606fa4f793.png)

**Comment by Mogli12** [comment]
Der Traktor hält nur die Himmerlsrichtung ein. Sollte es dabei etwas weg rutschen, dann muss man selber gegen lenken.

**Comment by Mogli12** [comment]
Ein kleines Problem beim halten der Fahrtrichtung konnte ich feststellen, was ich durch absichtliches leichtes Pendeln um die Mittellage in Version 0.0.0.5 von VCA versucht habe zu korrigieren.

**Comment by Mogli12** [comment]
Project is stopped as it does not work together with sleep on Dedi server.
