### ISSUE TITLE
Feature Request: Limit Throttle Tweak.

### ISSUE THREAD

**Issue by Harag9** [Mogli12/KeyboardSteer#94]
Loving the mod so far, makes keyboard driving much easier. However the limit throttle feature, what is the difference between

75/100  &
100/75

I've tried both settings and can't see a difference when in cruse control and press shift - just limits the speed by 75%,

So my thought would be the first option (75/100) would default to 75% speed, unless shift is pressed to go 100% speed (like a run key) - can this be added?

If this is how it's suppose to work, can you explain what I'm doing wrong?

**Comment by Mogli12** [comment]
If you press LShift than the cruise control speed is reduced to 75% in both casees 75/100 and 100/75. 

The first value is the value of acceleration pedal and max RPM if LShift is not pressed, the second value is valid if LShift is pressed.

The max speed is not limited, only the max RPM. This might of course limit max speed if max speed can only be reached at max RPM (e.g. Fendt 511).

**Comment by Harag9** [comment]
Excellent thanks for confirming this. As I'm playing on "starting from scratch" difficulty the only tractor I have at the moment is the cheap small Fendt which is slow, but powerful! I'll have a play with the settings on something more quicker. Loving the mod though - thanks!
