### ISSUE TITLE
Grad Anzeige ausblenden 

### ISSUE THREAD

**Issue by Einfllslos** [Mogli12/KeyboardSteer#95]
Kein Fehler sondern eine mögliche Verbesserung.
Könnte man in dem Menü auch die Grad Anzeige ein und ausblenden?
So wie man die anderen Funktionen auch ein und ausschalten kann.

**Comment by Eelijah666** [comment]
Das wäre perfekt! Ansonsten toller Mod !!!! Danke !!!

**Comment by Mogli12** [comment]
Das sind mir zu viele Schalter.

**Comment by DLH007** [comment]
Mogli, an welcher Stelle im Script müsste ich gucken um mir das selbst anzupassen? Datei/Zeile?

Danke.

**Comment by Mogli12** [comment]
Für Scripte an denen etwas geändert wurde übernehme ich keinen Support

**Comment by DLH007** [comment]
Nunja du sollst das ja auch nicht supporten, wenn dort Fehler entstehen, ist das ganz allein meine Sache. Eigentlich sollte es ja reichen die
`snapAngleHudX`
`snapAngleHudY`

auf einen Wert zu ändern, das sie nicht mehr auf dem Bildschirm zu sehen sind?

**Comment by Mogli12** [comment]
Du kannst auch einfach den Mod deinstallieren.

**Comment by DLH007** [comment]
Neeeeinnn, ich brauch ja das ShutttleControl und ich mag auch die GradAnzeige. Es gibt im Mulitplayer aber immer wieder Leute die das nicht mögen und denen Versuche ich es recht zu machen.
Warum reagierst du so?
