### ISSUE TITLE
Option to change position of worldposition and snapangle position from bottom right to top middle?

### ISSUE THREAD

**Issue by PitbullSpirit** [Mogli12/KeyboardSteer#96]
Hello,

I like to ask how / where if possible I can change position of worldposition and snapangle position from bottom right to top middle?

Another mod is having lots of small huds on that side (and can not re position them) and makes it impossble to read this mod for worldposition and snapangle when activated/on and friend said it was on top middle which I would actually dont mind if people put everything on bottom right.

So maybe as idea/option to re postion it by default or give people a choice where they want that info of course with all due respect if possible.

It is coming to a point me and others have to choose this mod or other mods due to their bottom right hud expanding information for vehicles etc.

Also asked this to them, but so far no luck.
I realize chances here are also slim for my question.

Thx anyways and sorry if I offended anyone, it is just a shame if I can't use some mods cause people like it at same spot as other have their mod.

**Comment by Mogli12** [comment]
Hi,

You can specify the position of the direction in the file modSettings/keyboardSteerMogliConfig.xml:
```xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<KSMGlobals>
	<snapAngleHudX       type="float" value="0.48"/> <!-- any value >= 0 => position of bottom left corner / -1 above HUD -->
	<snapAngleHudY       type="float" value="-0.95"/> <!-- any value >= 0 => position of bottom left corner / -1 above HUD -->
</KSMGlobals>
```

Regards,
Stefan
