### ISSUE TITLE
Wie funktioniert snapAngleHudY und X?

### ISSUE THREAD

**Issue by breadcan** [Mogli12/KeyboardSteer#99]
![2019-01-02 19_04_08-farming simulator 19](https://user-images.githubusercontent.com/416166/50605113-9737bc00-0ec1-11e9-8540-a5873b6cf618.png)

Ich würde gerne die Grad Anzeige rechts neben die Differentialsperrenanzeige legen. Mit 0 für die snapanglehudx/y liegt die Anzeige wie beschrieben ganz unten rechts. Mit "1" ist sie einfach weg, mit "20" auch.

**Comment by breadcan** [comment]
natürlich links neben die anzeige, nicht rechts...

**Comment by Mogli12** [comment]
Links unten ist 0, 0 und rechts oben ist 1, 1.

**Comment by Mogli12** [comment]
Relativ zum Hud kann man das nicht im Allgemeinen positionieren. Das hängt von der Auflösung und von der Größe des Huds ab. Ein Beispiel ist in #96.

**Comment by Mogli12** [comment]
P.S.: Den Mod TSX_EnhancedVehicle habe ich gesehen. Eigentlich hatte ich noch vor, GearboxAddon zu konvertieren. Aber das werde ich jetzt wohl nicht machen.

**Comment by breadcan** [comment]
Ah, mich irritierte, dass in der Config die Zahlen als Int definiert werden wenn die config erstellt wird:

    <snapAngleHudX value="-1" type="int"/>
    <snapAngleHudY value="-1" type="int"/>

Habe es jetzt mittig oben auf den Bildschirm gelegt:

    <snapAngleHudX value="0.5" type="float"/>
    <snapAngleHudY value="0.95" type="float"/>

Schade bzgl. GearboxAddon, vermisse das manuelle schalten.

**Comment by Mogli12** [comment]
Ich habe da mit DriveControl bereits genug schlechte Erfahrungen gesammelt. Ich habe Tage und Wochen damit verbracht, Incompatiblitäten zw. GearboxAddon und DriveControl auszubügeln. Das werde ich nicht nochmal machen.

**Comment by Einfllslos** [comment]
Sehr sehr schade das mit GB. Kann ich natürlich nachvollziehen, aber bin jetzt etwas traurig :(
Habe den TSX_EnhancedVehicle als Übergangslösung bis GB kommt installiert, danach hätte ich ihn nicht mehr gebraucht aber jetzt heißt es wohl hoffen dass von Giants was in Richtung Getriebe kommt. :/

**Comment by bgo1973** [comment]
Das wär' mal was. Die Hoffnung stirbt bekanntlich zuletzt. Naja, die Daten der einzelnen gearratios sind in den xml ja bereits vorhanden. Wer weiß.
